// Code generated by protoc-gen-connect-go. DO NOT EDIT.
// This is a placeholder file. Regenerate using buf generate.

package tokensconnect

import (
	context "context"

	connect "connectrpc.com/connect"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	tokens "github.com/scalekit-inc/scalekit-sdk-go/v2/pkg/grpc/scalekit/v1/tokens"
)

const (
	ApiTokenServiceName = "scalekit.v1.tokens.ApiTokenService"
)

const (
	ApiTokenServiceCreateTokenProcedure     = "/scalekit.v1.tokens.ApiTokenService/CreateToken"
	ApiTokenServiceValidateTokenProcedure   = "/scalekit.v1.tokens.ApiTokenService/ValidateToken"
	ApiTokenServiceInvalidateTokenProcedure = "/scalekit.v1.tokens.ApiTokenService/InvalidateToken"
	ApiTokenServiceListTokensProcedure      = "/scalekit.v1.tokens.ApiTokenService/ListTokens"
)

type ApiTokenServiceClient interface {
	CreateToken(context.Context, *connect.Request[tokens.CreateTokenRequest]) (*connect.Response[tokens.CreateTokenResponse], error)
	ValidateToken(context.Context, *connect.Request[tokens.ValidateTokenRequest]) (*connect.Response[tokens.ValidateTokenResponse], error)
	InvalidateToken(context.Context, *connect.Request[tokens.InvalidateTokenRequest]) (*connect.Response[emptypb.Empty], error)
	ListTokens(context.Context, *connect.Request[tokens.ListTokensRequest]) (*connect.Response[tokens.ListTokensResponse], error)
}

func NewApiTokenServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ApiTokenServiceClient {
	return &apiTokenServiceClient{
		createToken: connect.NewClient[tokens.CreateTokenRequest, tokens.CreateTokenResponse](
			httpClient,
			baseURL+ApiTokenServiceCreateTokenProcedure,
			opts...,
		),
		validateToken: connect.NewClient[tokens.ValidateTokenRequest, tokens.ValidateTokenResponse](
			httpClient,
			baseURL+ApiTokenServiceValidateTokenProcedure,
			opts...,
		),
		invalidateToken: connect.NewClient[tokens.InvalidateTokenRequest, emptypb.Empty](
			httpClient,
			baseURL+ApiTokenServiceInvalidateTokenProcedure,
			opts...,
		),
		listTokens: connect.NewClient[tokens.ListTokensRequest, tokens.ListTokensResponse](
			httpClient,
			baseURL+ApiTokenServiceListTokensProcedure,
			opts...,
		),
	}
}

type apiTokenServiceClient struct {
	createToken     *connect.Client[tokens.CreateTokenRequest, tokens.CreateTokenResponse]
	validateToken   *connect.Client[tokens.ValidateTokenRequest, tokens.ValidateTokenResponse]
	invalidateToken *connect.Client[tokens.InvalidateTokenRequest, emptypb.Empty]
	listTokens      *connect.Client[tokens.ListTokensRequest, tokens.ListTokensResponse]
}

func (c *apiTokenServiceClient) CreateToken(ctx context.Context, req *connect.Request[tokens.CreateTokenRequest]) (*connect.Response[tokens.CreateTokenResponse], error) {
	return c.createToken.CallUnary(ctx, req)
}

func (c *apiTokenServiceClient) ValidateToken(ctx context.Context, req *connect.Request[tokens.ValidateTokenRequest]) (*connect.Response[tokens.ValidateTokenResponse], error) {
	return c.validateToken.CallUnary(ctx, req)
}

func (c *apiTokenServiceClient) InvalidateToken(ctx context.Context, req *connect.Request[tokens.InvalidateTokenRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.invalidateToken.CallUnary(ctx, req)
}

func (c *apiTokenServiceClient) ListTokens(ctx context.Context, req *connect.Request[tokens.ListTokensRequest]) (*connect.Response[tokens.ListTokensResponse], error) {
	return c.listTokens.CallUnary(ctx, req)
}
