// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scalekit/v1/auth/auth.proto

package auth

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	connections "github.com/scalekit-inc/scalekit-sdk-go/v2/pkg/grpc/scalekit/v1/connections"
	_ "github.com/scalekit-inc/scalekit-sdk-go/v2/pkg/grpc/scalekit/v1/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Intent int32

const (
	Intent_INTENT_UNSPECIFIED Intent = 0
	Intent_sign_in            Intent = 1
	Intent_sign_up            Intent = 2
)

// Enum value maps for Intent.
var (
	Intent_name = map[int32]string{
		0: "INTENT_UNSPECIFIED",
		1: "sign_in",
		2: "sign_up",
	}
	Intent_value = map[string]int32{
		"INTENT_UNSPECIFIED": 0,
		"sign_in":            1,
		"sign_up":            2,
	}
)

func (x Intent) Enum() *Intent {
	p := new(Intent)
	*p = x
	return p
}

func (x Intent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Intent) Descriptor() protoreflect.EnumDescriptor {
	return file_scalekit_v1_auth_auth_proto_enumTypes[0].Descriptor()
}

func (Intent) Type() protoreflect.EnumType {
	return &file_scalekit_v1_auth_auth_proto_enumTypes[0]
}

func (x Intent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Intent.Descriptor instead.
func (Intent) EnumDescriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{0}
}

type AuthState int32

const (
	AuthState_AUTH_STATE_UNSPECIFIED             AuthState = 0
	AuthState_AUTHENTICATION_IN_PROGRESS         AuthState = 1
	AuthState_ORGANIZATION_SWITCHER              AuthState = 2
	AuthState_ORGANIZATION_SELECTED              AuthState = 3
	AuthState_ORGANIZATION_SIGNUP                AuthState = 4
	AuthState_ORGANIZATION_SWITCHER_SIGNUP       AuthState = 5
	AuthState_OTP_VERIFICATION_PENDING           AuthState = 6
	AuthState_MAGIC_LINK_SENT                    AuthState = 7
	AuthState_LINK_SENT_OTP_VERIFICATION_PENDING AuthState = 8
	AuthState_OTP_VERIFIED                       AuthState = 9
	AuthState_LINK_VERIFIED                      AuthState = 10
	AuthState_SSO_AUTHENTICATED                  AuthState = 11
	AuthState_ORG_USER_CREATED                   AuthState = 12
	AuthState_AUTHENTICATION_COMPLETED           AuthState = 13
	AuthState_AUTHENTICATION_FAILED              AuthState = 14
	AuthState_WEBAUTHN_VERIFIED                  AuthState = 15
	AuthState_VERIFICATION_MAGIC_LINK_SENT       AuthState = 16
	AuthState_VERIFICATION_MAGIC_LINK_OTP_SENT   AuthState = 17
	AuthState_VERIFICATION_OTP_SENT              AuthState = 18
	AuthState_VERIFICATION_COMPLETED             AuthState = 19
)

// Enum value maps for AuthState.
var (
	AuthState_name = map[int32]string{
		0:  "AUTH_STATE_UNSPECIFIED",
		1:  "AUTHENTICATION_IN_PROGRESS",
		2:  "ORGANIZATION_SWITCHER",
		3:  "ORGANIZATION_SELECTED",
		4:  "ORGANIZATION_SIGNUP",
		5:  "ORGANIZATION_SWITCHER_SIGNUP",
		6:  "OTP_VERIFICATION_PENDING",
		7:  "MAGIC_LINK_SENT",
		8:  "LINK_SENT_OTP_VERIFICATION_PENDING",
		9:  "OTP_VERIFIED",
		10: "LINK_VERIFIED",
		11: "SSO_AUTHENTICATED",
		12: "ORG_USER_CREATED",
		13: "AUTHENTICATION_COMPLETED",
		14: "AUTHENTICATION_FAILED",
		15: "WEBAUTHN_VERIFIED",
		16: "VERIFICATION_MAGIC_LINK_SENT",
		17: "VERIFICATION_MAGIC_LINK_OTP_SENT",
		18: "VERIFICATION_OTP_SENT",
		19: "VERIFICATION_COMPLETED",
	}
	AuthState_value = map[string]int32{
		"AUTH_STATE_UNSPECIFIED":             0,
		"AUTHENTICATION_IN_PROGRESS":         1,
		"ORGANIZATION_SWITCHER":              2,
		"ORGANIZATION_SELECTED":              3,
		"ORGANIZATION_SIGNUP":                4,
		"ORGANIZATION_SWITCHER_SIGNUP":       5,
		"OTP_VERIFICATION_PENDING":           6,
		"MAGIC_LINK_SENT":                    7,
		"LINK_SENT_OTP_VERIFICATION_PENDING": 8,
		"OTP_VERIFIED":                       9,
		"LINK_VERIFIED":                      10,
		"SSO_AUTHENTICATED":                  11,
		"ORG_USER_CREATED":                   12,
		"AUTHENTICATION_COMPLETED":           13,
		"AUTHENTICATION_FAILED":              14,
		"WEBAUTHN_VERIFIED":                  15,
		"VERIFICATION_MAGIC_LINK_SENT":       16,
		"VERIFICATION_MAGIC_LINK_OTP_SENT":   17,
		"VERIFICATION_OTP_SENT":              18,
		"VERIFICATION_COMPLETED":             19,
	}
)

func (x AuthState) Enum() *AuthState {
	p := new(AuthState)
	*p = x
	return p
}

func (x AuthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthState) Descriptor() protoreflect.EnumDescriptor {
	return file_scalekit_v1_auth_auth_proto_enumTypes[1].Descriptor()
}

func (AuthState) Type() protoreflect.EnumType {
	return &file_scalekit_v1_auth_auth_proto_enumTypes[1]
}

func (x AuthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthState.Descriptor instead.
func (AuthState) EnumDescriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{1}
}

type ListAuthMethodsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intent        string                 `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthMethodsRequest) Reset() {
	*x = ListAuthMethodsRequest{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthMethodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthMethodsRequest) ProtoMessage() {}

func (x *ListAuthMethodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthMethodsRequest.ProtoReflect.Descriptor instead.
func (*ListAuthMethodsRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ListAuthMethodsRequest) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

type ListAuthMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthMethods   []*AuthMethod          `protobuf:"bytes,1,rep,name=auth_methods,json=authMethods,proto3" json:"auth_methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthMethodsResponse) Reset() {
	*x = ListAuthMethodsResponse{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthMethodsResponse) ProtoMessage() {}

func (x *ListAuthMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthMethodsResponse.ProtoReflect.Descriptor instead.
func (*ListAuthMethodsResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ListAuthMethodsResponse) GetAuthMethods() []*AuthMethod {
	if x != nil {
		return x.AuthMethods
	}
	return nil
}

type AuthMethod struct {
	state                          protoimpl.MessageState        `protogen:"open.v1"`
	ConnectionId                   string                        `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ConnectionType                 connections.ConnectionType    `protobuf:"varint,2,opt,name=connection_type,json=connectionType,proto3,enum=scalekit.v1.connections.ConnectionType" json:"connection_type,omitempty"`
	Provider                       string                        `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	AuthInitiationUri              string                        `protobuf:"bytes,4,opt,name=auth_initiation_uri,json=authInitiationUri,proto3" json:"auth_initiation_uri,omitempty"`
	PasswordlessType               *connections.PasswordlessType `protobuf:"varint,5,opt,name=passwordless_type,json=passwordlessType,proto3,enum=scalekit.v1.connections.PasswordlessType,oneof" json:"passwordless_type,omitempty"`
	CodeChallengeLength            *uint32                       `protobuf:"varint,6,opt,name=code_challenge_length,json=codeChallengeLength,proto3,oneof" json:"code_challenge_length,omitempty"`
	EnableWebauthnAutoRegistration *bool                         `protobuf:"varint,7,opt,name=enable_webauthn_auto_registration,json=enableWebauthnAutoRegistration,proto3,oneof" json:"enable_webauthn_auto_registration,omitempty"`
	ShowPasskeyButton              *bool                         `protobuf:"varint,8,opt,name=show_passkey_button,json=showPasskeyButton,proto3,oneof" json:"show_passkey_button,omitempty"`
	EnableWebauthnConditionalLogin *bool                         `protobuf:"varint,9,opt,name=enable_webauthn_conditional_login,json=enableWebauthnConditionalLogin,proto3,oneof" json:"enable_webauthn_conditional_login,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *AuthMethod) Reset() {
	*x = AuthMethod{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMethod) ProtoMessage() {}

func (x *AuthMethod) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMethod.ProtoReflect.Descriptor instead.
func (*AuthMethod) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthMethod) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *AuthMethod) GetConnectionType() connections.ConnectionType {
	if x != nil {
		return x.ConnectionType
	}
	return connections.ConnectionType(0)
}

func (x *AuthMethod) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AuthMethod) GetAuthInitiationUri() string {
	if x != nil {
		return x.AuthInitiationUri
	}
	return ""
}

func (x *AuthMethod) GetPasswordlessType() connections.PasswordlessType {
	if x != nil && x.PasswordlessType != nil {
		return *x.PasswordlessType
	}
	return connections.PasswordlessType(0)
}

func (x *AuthMethod) GetCodeChallengeLength() uint32 {
	if x != nil && x.CodeChallengeLength != nil {
		return *x.CodeChallengeLength
	}
	return 0
}

func (x *AuthMethod) GetEnableWebauthnAutoRegistration() bool {
	if x != nil && x.EnableWebauthnAutoRegistration != nil {
		return *x.EnableWebauthnAutoRegistration
	}
	return false
}

func (x *AuthMethod) GetShowPasskeyButton() bool {
	if x != nil && x.ShowPasskeyButton != nil {
		return *x.ShowPasskeyButton
	}
	return false
}

func (x *AuthMethod) GetEnableWebauthnConditionalLogin() bool {
	if x != nil && x.EnableWebauthnConditionalLogin != nil {
		return *x.EnableWebauthnConditionalLogin
	}
	return false
}

type DiscoveryAuthMethodRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DiscoveryRequest *DiscoveryRequest      `protobuf:"bytes,2,opt,name=discovery_request,json=discoveryRequest,proto3" json:"discovery_request,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiscoveryAuthMethodRequest) Reset() {
	*x = DiscoveryAuthMethodRequest{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryAuthMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryAuthMethodRequest) ProtoMessage() {}

func (x *DiscoveryAuthMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryAuthMethodRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryAuthMethodRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoveryAuthMethodRequest) GetDiscoveryRequest() *DiscoveryRequest {
	if x != nil {
		return x.DiscoveryRequest
	}
	return nil
}

type DiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Intent        Intent                 `protobuf:"varint,2,opt,name=intent,proto3,enum=scalekit.v1.auth.Intent" json:"intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoveryRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DiscoveryRequest) GetIntent() Intent {
	if x != nil {
		return x.Intent
	}
	return Intent_INTENT_UNSPECIFIED
}

type DiscoveryAuthMethodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthMethod    *AuthMethod            `protobuf:"bytes,1,opt,name=auth_method,json=authMethod,proto3" json:"auth_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryAuthMethodResponse) Reset() {
	*x = DiscoveryAuthMethodResponse{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryAuthMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryAuthMethodResponse) ProtoMessage() {}

func (x *DiscoveryAuthMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryAuthMethodResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryAuthMethodResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoveryAuthMethodResponse) GetAuthMethod() *AuthMethod {
	if x != nil {
		return x.AuthMethod
	}
	return nil
}

type GetAuthCustomizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthCustomizationsRequest) Reset() {
	*x = GetAuthCustomizationsRequest{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthCustomizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthCustomizationsRequest) ProtoMessage() {}

func (x *GetAuthCustomizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthCustomizationsRequest.ProtoReflect.Descriptor instead.
func (*GetAuthCustomizationsRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{6}
}

// PortalSettings contains feature flags and settings derived from the workspace's billing subscription
type PortalSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// custom_branding indicates whether the workspace has the Customization billing item enabled,
	// allowing custom portal branding (logos, colors, etc.)
	CustomBranding bool `protobuf:"varint,1,opt,name=custom_branding,json=customBranding,proto3" json:"custom_branding,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PortalSettings) Reset() {
	*x = PortalSettings{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortalSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortalSettings) ProtoMessage() {}

func (x *PortalSettings) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortalSettings.ProtoReflect.Descriptor instead.
func (*PortalSettings) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *PortalSettings) GetCustomBranding() bool {
	if x != nil {
		return x.CustomBranding
	}
	return false
}

type GetAuthCustomizationsResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CustomizationSettings *structpb.Struct       `protobuf:"bytes,2,opt,name=customization_settings,json=customizationSettings,proto3" json:"customization_settings,omitempty"`
	// settings contains feature flags derived from the workspace's billing subscription
	Settings      *PortalSettings `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthCustomizationsResponse) Reset() {
	*x = GetAuthCustomizationsResponse{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthCustomizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthCustomizationsResponse) ProtoMessage() {}

func (x *GetAuthCustomizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthCustomizationsResponse.ProtoReflect.Descriptor instead.
func (*GetAuthCustomizationsResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *GetAuthCustomizationsResponse) GetCustomizationSettings() *structpb.Struct {
	if x != nil {
		return x.CustomizationSettings
	}
	return nil
}

func (x *GetAuthCustomizationsResponse) GetSettings() *PortalSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetAuthFeaturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      *structpb.Struct       `protobuf:"bytes,1,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthFeaturesResponse) Reset() {
	*x = GetAuthFeaturesResponse{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthFeaturesResponse) ProtoMessage() {}

func (x *GetAuthFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthFeaturesResponse.ProtoReflect.Descriptor instead.
func (*GetAuthFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *GetAuthFeaturesResponse) GetFeatures() *structpb.Struct {
	if x != nil {
		return x.Features
	}
	return nil
}

type VerifyPasswordLessOtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OtpReq        *OTPRequest            `protobuf:"bytes,2,opt,name=otp_req,json=otpReq,proto3" json:"otp_req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordLessOtpRequest) Reset() {
	*x = VerifyPasswordLessOtpRequest{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordLessOtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordLessOtpRequest) ProtoMessage() {}

func (x *VerifyPasswordLessOtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordLessOtpRequest.ProtoReflect.Descriptor instead.
func (*VerifyPasswordLessOtpRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyPasswordLessOtpRequest) GetOtpReq() *OTPRequest {
	if x != nil {
		return x.OtpReq
	}
	return nil
}

type VerifyPasswordLessOtpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPasswordLessOtpResponse) Reset() {
	*x = VerifyPasswordLessOtpResponse{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordLessOtpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordLessOtpResponse) ProtoMessage() {}

func (x *VerifyPasswordLessOtpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordLessOtpResponse.ProtoReflect.Descriptor instead.
func (*VerifyPasswordLessOtpResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{11}
}

type OTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeChallenge string                 `protobuf:"bytes,1,opt,name=code_challenge,json=codeChallenge,proto3" json:"code_challenge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTPRequest) Reset() {
	*x = OTPRequest{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTPRequest) ProtoMessage() {}

func (x *OTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTPRequest.ProtoReflect.Descriptor instead.
func (*OTPRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{12}
}

func (x *OTPRequest) GetCodeChallenge() string {
	if x != nil {
		return x.CodeChallenge
	}
	return ""
}

type ListUserOrganizationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organizations []*Organization        `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	User          *UserDetails           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Intent        Intent                 `protobuf:"varint,3,opt,name=intent,proto3,enum=scalekit.v1.auth.Intent" json:"intent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserOrganizationsResponse) Reset() {
	*x = ListUserOrganizationsResponse{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserOrganizationsResponse) ProtoMessage() {}

func (x *ListUserOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListUserOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{13}
}

func (x *ListUserOrganizationsResponse) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *ListUserOrganizationsResponse) GetUser() *UserDetails {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ListUserOrganizationsResponse) GetIntent() Intent {
	if x != nil {
		return x.Intent
	}
	return Intent_INTENT_UNSPECIFIED
}

type Organization struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MembershipStatus       string                 `protobuf:"bytes,3,opt,name=membership_status,json=membershipStatus,proto3" json:"membership_status,omitempty"`
	InvitationInviterEmail *string                `protobuf:"bytes,4,opt,name=invitation_inviter_email,json=invitationInviterEmail,proto3,oneof" json:"invitation_inviter_email,omitempty"`
	InvitationAcceptedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=invitation_accepted_at,json=invitationAcceptedAt,proto3,oneof" json:"invitation_accepted_at,omitempty"`
	InvitationCreatedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=invitation_created_at,json=invitationCreatedAt,proto3,oneof" json:"invitation_created_at,omitempty"`
	InvitationExpiresAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=invitation_expires_at,json=invitationExpiresAt,proto3,oneof" json:"invitation_expires_at,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{14}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetMembershipStatus() string {
	if x != nil {
		return x.MembershipStatus
	}
	return ""
}

func (x *Organization) GetInvitationInviterEmail() string {
	if x != nil && x.InvitationInviterEmail != nil {
		return *x.InvitationInviterEmail
	}
	return ""
}

func (x *Organization) GetInvitationAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InvitationAcceptedAt
	}
	return nil
}

func (x *Organization) GetInvitationCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InvitationCreatedAt
	}
	return nil
}

func (x *Organization) GetInvitationExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InvitationExpiresAt
	}
	return nil
}

type UserDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetails) Reset() {
	*x = UserDetails{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetails) ProtoMessage() {}

func (x *UserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetails.ProtoReflect.Descriptor instead.
func (*UserDetails) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{15}
}

func (x *UserDetails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDetails) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserDetails) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type SignupOrganizationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// making all optional for now
	OrganizationName string `protobuf:"bytes,1,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	FirstName        string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	FullName         string `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber      string `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignupOrganizationRequest) Reset() {
	*x = SignupOrganizationRequest{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupOrganizationRequest) ProtoMessage() {}

func (x *SignupOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupOrganizationRequest.ProtoReflect.Descriptor instead.
func (*SignupOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{16}
}

func (x *SignupOrganizationRequest) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *SignupOrganizationRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SignupOrganizationRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SignupOrganizationRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *SignupOrganizationRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type SignupOrganizationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId   string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName string                 `protobuf:"bytes,2,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignupOrganizationResponse) Reset() {
	*x = SignupOrganizationResponse{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupOrganizationResponse) ProtoMessage() {}

func (x *SignupOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupOrganizationResponse.ProtoReflect.Descriptor instead.
func (*SignupOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{17}
}

func (x *SignupOrganizationResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SignupOrganizationResponse) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

type UpdateLoginUserDetailsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId   string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	LoginRequestId string                 `protobuf:"bytes,2,opt,name=login_request_id,json=loginRequestId,proto3" json:"login_request_id,omitempty"`
	User           *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLoginUserDetailsRequest) Reset() {
	*x = UpdateLoginUserDetailsRequest{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoginUserDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoginUserDetailsRequest) ProtoMessage() {}

func (x *UpdateLoginUserDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoginUserDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateLoginUserDetailsRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateLoginUserDetailsRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *UpdateLoginUserDetailsRequest) GetLoginRequestId() string {
	if x != nil {
		return x.LoginRequestId
	}
	return ""
}

func (x *UpdateLoginUserDetailsRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Sub                    string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	Email                  string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	GivenName              string                 `protobuf:"bytes,3,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName             string                 `protobuf:"bytes,4,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	EmailVerified          bool                   `protobuf:"varint,5,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	PhoneNumber            string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	PhoneNumberVerified    bool                   `protobuf:"varint,7,opt,name=phone_number_verified,json=phoneNumberVerified,proto3" json:"phone_number_verified,omitempty"`
	Name                   string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	PreferredUsername      string                 `protobuf:"bytes,9,opt,name=preferred_username,json=preferredUsername,proto3" json:"preferred_username,omitempty"`
	Picture                string                 `protobuf:"bytes,10,opt,name=picture,proto3" json:"picture,omitempty"`
	Gender                 string                 `protobuf:"bytes,11,opt,name=gender,proto3" json:"gender,omitempty"`
	Locale                 string                 `protobuf:"bytes,12,opt,name=locale,proto3" json:"locale,omitempty"`
	Groups                 []string               `protobuf:"bytes,13,rep,name=groups,proto3" json:"groups,omitempty"`
	CustomAttributes       *structpb.Struct       `protobuf:"bytes,14,opt,name=custom_attributes,json=customAttributes,proto3" json:"custom_attributes,omitempty"`
	OrganizationExternalId *string                `protobuf:"bytes,15,opt,name=organization_external_id,json=organizationExternalId,proto3,oneof" json:"organization_external_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{19}
}

func (x *User) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *User) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetPhoneNumberVerified() bool {
	if x != nil {
		return x.PhoneNumberVerified
	}
	return false
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetPreferredUsername() string {
	if x != nil {
		return x.PreferredUsername
	}
	return ""
}

func (x *User) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *User) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *User) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *User) GetCustomAttributes() *structpb.Struct {
	if x != nil {
		return x.CustomAttributes
	}
	return nil
}

func (x *User) GetOrganizationExternalId() string {
	if x != nil && x.OrganizationExternalId != nil {
		return *x.OrganizationExternalId
	}
	return ""
}

type GetAuthStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthState     AuthState              `protobuf:"varint,1,opt,name=auth_state,json=authState,proto3,enum=scalekit.v1.auth.AuthState" json:"auth_state,omitempty"`
	User          *UserDetails           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthStateResponse) Reset() {
	*x = GetAuthStateResponse{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthStateResponse) ProtoMessage() {}

func (x *GetAuthStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthStateResponse.ProtoReflect.Descriptor instead.
func (*GetAuthStateResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{20}
}

func (x *GetAuthStateResponse) GetAuthState() AuthState {
	if x != nil {
		return x.AuthState
	}
	return AuthState_AUTH_STATE_UNSPECIFIED
}

func (x *GetAuthStateResponse) GetUser() *UserDetails {
	if x != nil {
		return x.User
	}
	return nil
}

type GetAuthErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorId       string                 `protobuf:"bytes,1,opt,name=error_id,json=errorId,proto3" json:"error_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthErrorRequest) Reset() {
	*x = GetAuthErrorRequest{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthErrorRequest) ProtoMessage() {}

func (x *GetAuthErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthErrorRequest.ProtoReflect.Descriptor instead.
func (*GetAuthErrorRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{21}
}

func (x *GetAuthErrorRequest) GetErrorId() string {
	if x != nil {
		return x.ErrorId
	}
	return ""
}

type GetAuthErrorResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Error            string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorDescription string                 `protobuf:"bytes,2,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAuthErrorResponse) Reset() {
	*x = GetAuthErrorResponse{}
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthErrorResponse) ProtoMessage() {}

func (x *GetAuthErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthErrorResponse.ProtoReflect.Descriptor instead.
func (*GetAuthErrorResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_auth_proto_rawDescGZIP(), []int{22}
}

func (x *GetAuthErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetAuthErrorResponse) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

var File_scalekit_v1_auth_auth_proto protoreflect.FileDescriptor

const file_scalekit_v1_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x1bscalekit/v1/auth/auth.proto\x12\x10scalekit.v1.auth\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/api/visibility.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a)scalekit/v1/connections/connections.proto\x1a!scalekit/v1/options/options.proto\"0\n" +
	"\x16ListAuthMethodsRequest\x12\x16\n" +
	"\x06intent\x18\x01 \x01(\tR\x06intent\"Z\n" +
	"\x17ListAuthMethodsResponse\x12?\n" +
	"\fauth_methods\x18\x01 \x03(\v2\x1c.scalekit.v1.auth.AuthMethodR\vauthMethods\"\x89\t\n" +
	"\n" +
	"AuthMethod\x12}\n" +
	"\rconnection_id\x18\x01 \x01(\tBX\x92AL22Unique identifier for the connection to be toggledJ\x16\"conn_121312434123312\"\xbaH\x06r\x04\x10\x01\x18 R\fconnectionId\x12P\n" +
	"\x0fconnection_type\x18\x02 \x01(\x0e2'.scalekit.v1.connections.ConnectionTypeR\x0econnectionType\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x93\x01\n" +
	"\x13auth_initiation_uri\x18\x04 \x01(\tBc\x92AV2\x1eURI to initiate the connectionJ4\"https://sso.acmecorp.com/sso/v1/oidc/conn_123/init\"\xbaH\ar\x05\x10\x01\x18\xff\x01R\x11authInitiationUri\x12z\n" +
	"\x11passwordless_type\x18\x05 \x01(\x0e2).scalekit.v1.connections.PasswordlessTypeB\x1d\x92A\x1a2\x11Passwordless typeJ\x05\"OTP\"H\x00R\x10passwordlessType\x88\x01\x01\x12W\n" +
	"\x15code_challenge_length\x18\x06 \x01(\rB\x1e\x92A\x1b2\x16Length of the OTP codeJ\x016H\x01R\x13codeChallengeLength\x88\x01\x01\x12\xa3\x01\n" +
	"!enable_webauthn_auto_registration\x18\a \x01(\bBS\x92AP2GIndicates if WebAuthn auto-registration is enabled for this auth method:\x05falseH\x02R\x1eenableWebauthnAutoRegistration\x88\x01\x01\x12c\n" +
	"\x13show_passkey_button\x18\b \x01(\bB.\x92A+2#Show passkey button on login screen:\x04trueH\x03R\x11showPasskeyButton\x88\x01\x01\x12\x83\x01\n" +
	"!enable_webauthn_conditional_login\x18\t \x01(\bB3\x92A02(Allow autofill of passkeys in login page:\x04trueH\x04R\x1eenableWebauthnConditionalLogin\x88\x01\x01B\x14\n" +
	"\x12_passwordless_typeB\x18\n" +
	"\x16_code_challenge_lengthB$\n" +
	"\"_enable_webauthn_auto_registrationB\x16\n" +
	"\x14_show_passkey_buttonB$\n" +
	"\"_enable_webauthn_conditional_login\"m\n" +
	"\x1aDiscoveryAuthMethodRequest\x12O\n" +
	"\x11discovery_request\x18\x02 \x01(\v2\".scalekit.v1.auth.DiscoveryRequestR\x10discoveryRequest\"\xb3\x01\n" +
	"\x10DiscoveryRequest\x12c\n" +
	"\x05email\x18\x01 \x01(\tBM\x92AA2*user identifier like email or phone numberJ\x13\"john@acmecorp.com\"\xbaH\x06r\x04\x10\x03\x18dR\x05email\x12:\n" +
	"\x06intent\x18\x02 \x01(\x0e2\x18.scalekit.v1.auth.IntentB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06intent\"\\\n" +
	"\x1bDiscoveryAuthMethodResponse\x12=\n" +
	"\vauth_method\x18\x01 \x01(\v2\x1c.scalekit.v1.auth.AuthMethodR\n" +
	"authMethod\"\x1e\n" +
	"\x1cGetAuthCustomizationsRequest\"\xab\x01\n" +
	"\x0ePortalSettings\x12\x98\x01\n" +
	"\x0fcustom_branding\x18\x01 \x01(\bBo\x92Al2dIndicates whether custom portal branding is enabled for this workspace based on billing subscriptionJ\x04trueR\x0ecustomBranding\"\xb2\x01\n" +
	"\x1dGetAuthCustomizationsResponse\x12N\n" +
	"\x16customization_settings\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x15customizationSettings\x12A\n" +
	"\bsettings\x18\x03 \x01(\v2 .scalekit.v1.auth.PortalSettingsB\x03\xe0A\x03R\bsettings\"N\n" +
	"\x17GetAuthFeaturesResponse\x123\n" +
	"\bfeatures\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bfeatures\"U\n" +
	"\x1cVerifyPasswordLessOtpRequest\x125\n" +
	"\aotp_req\x18\x02 \x01(\v2\x1c.scalekit.v1.auth.OTPRequestR\x06otpReq\"\x1f\n" +
	"\x1dVerifyPasswordLessOtpResponse\"i\n" +
	"\n" +
	"OTPRequest\x12[\n" +
	"\x0ecode_challenge\x18\x01 \x01(\tB4\x92A(2\x1cOTP sent to the user's emailJ\b\"123456\"\xbaH\x06r\x04\x10\x05\x18\x06R\rcodeChallenge\"\xd4\x01\n" +
	"\x1dListUserOrganizationsResponse\x12D\n" +
	"\rorganizations\x18\x01 \x03(\v2\x1e.scalekit.v1.auth.OrganizationR\rorganizations\x121\n" +
	"\x04user\x18\x02 \x01(\v2\x1d.scalekit.v1.auth.UserDetailsR\x04user\x12:\n" +
	"\x06intent\x18\x03 \x01(\x0e2\x18.scalekit.v1.auth.IntentB\b\xbaH\x05\x82\x01\x02\x10\x01R\x06intent\"\x8b\x04\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x11membership_status\x18\x03 \x01(\tR\x10membershipStatus\x12=\n" +
	"\x18invitation_inviter_email\x18\x04 \x01(\tH\x00R\x16invitationInviterEmail\x88\x01\x01\x12U\n" +
	"\x16invitation_accepted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x14invitationAcceptedAt\x88\x01\x01\x12S\n" +
	"\x15invitation_created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x13invitationCreatedAt\x88\x01\x01\x12S\n" +
	"\x15invitation_expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x13invitationExpiresAt\x88\x01\x01B\x1b\n" +
	"\x19_invitation_inviter_emailB\x19\n" +
	"\x17_invitation_accepted_atB\x18\n" +
	"\x16_invitation_created_atB\x18\n" +
	"\x16_invitation_expires_at\"_\n" +
	"\vUserDetails\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\"\xc4\x01\n" +
	"\x19SignupOrganizationRequest\x12+\n" +
	"\x11organization_name\x18\x01 \x01(\tR\x10organizationName\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\"r\n" +
	"\x1aSignupOrganizationResponse\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12+\n" +
	"\x11organization_name\x18\x02 \x01(\tR\x10organizationName\"\xd6\x02\n" +
	"\x1dUpdateLoginUserDetailsRequest\x12v\n" +
	"\rconnection_id\x18\x01 \x01(\tBQ\x92AE2+Connection ID. Unique ID for the connectionJ\x16\"conn_121312434123312\"\xbaH\x06r\x04\x10\x01\x18 R\fconnectionId\x12\x90\x01\n" +
	"\x10login_request_id\x18\x02 \x01(\tBf\x92A]2BLogin Request ID that was shared as part of authorization initiateJ\x17\"lri_73415099636808061\"\xbaH\x03\xc8\x01\x01R\x0eloginRequestId\x12*\n" +
	"\x04user\x18\x03 \x01(\v2\x16.scalekit.v1.auth.UserR\x04user\"\xe1\r\n" +
	"\x04User\x12\x83\x01\n" +
	"\x03sub\x18\x01 \x01(\tBq\x92Ag2WSubject identifier for the user (typically a unique user ID from the identity provider)J\f\"1234567890\"\xbaH\x04r\x02\x10\x01R\x03sub\x12R\n" +
	"\x05email\x18\x02 \x01(\tB<\x92A22\x1cUser's primary email addressJ\x12\"user@example.com\"\xbaH\x04r\x02\x10\x01R\x05email\x12=\n" +
	"\n" +
	"given_name\x18\x03 \x01(\tB\x1e\x92A\x1b2\x11User's first nameJ\x06\"John\"R\tgivenName\x12=\n" +
	"\vfamily_name\x18\x04 \x01(\tB\x1c\x92A\x192\x10User's last nameJ\x05\"Doe\"R\n" +
	"familyName\x12\x88\x01\n" +
	"\x0eemail_verified\x18\x05 \x01(\bBa\x92A^2VIndicates whether the user's email address has been verified by the identity provider.J\x04trueR\remailVerified\x12c\n" +
	"\fphone_number\x18\x06 \x01(\tB@\x92A=2,User's primary phone number in E.164 format.J\r\"+1234567890\"R\vphoneNumber\x12\x95\x01\n" +
	"\x15phone_number_verified\x18\a \x01(\bBa\x92A^2UIndicates whether the user's phone number has been verified by the identity provider.J\x05falseR\x13phoneNumberVerified\x12B\n" +
	"\x04name\x18\b \x01(\tB.\x92A+2\x1dFull display name of the userJ\n" +
	"\"John Doe\"R\x04name\x12b\n" +
	"\x12preferred_username\x18\t \x01(\tB3\x92A02#User's preferred username or handleJ\t\"johndoe\"R\x11preferredUsername\x12b\n" +
	"\apicture\x18\n" +
	" \x01(\tBH\x92AE2!URL to the user's profile pictureJ \"https://example.com/avatar.jpg\"R\apicture\x12X\n" +
	"\x06gender\x18\v \x01(\tB@\x92A=23User's gender as reported by the identity provider.J\x06\"male\"R\x06gender\x12e\n" +
	"\x06locale\x18\f \x01(\tBM\x92AJ2?User's locale or language preference (IETF BCP 47 language tag)J\a\"en-US\"R\x06locale\x12f\n" +
	"\x06groups\x18\r \x03(\tBN\x92AK2/List of group names or IDs the user belongs to.J\x18[\"admins\", \"developers\"]R\x06groups\x12\xf2\x01\n" +
	"\x11custom_attributes\x18\x0e \x01(\v2\x17.google.protobuf.StructB\xab\x01\x92A\xa7\x012mCustom attributes for the user, represented as a key-value map. Used for additional identity provider claims.J6{\"department\": \"Engineering\", \"employee_id\": \"E12345\"}R\x10customAttributes\x12\xb1\x01\n" +
	"\x18organization_external_id\x18\x0f \x01(\tBr\x92Ao2EIdentifier for the user’s organization within the identity providerJ&\"132d085d-d89d-4a2e-95bb-49bde680d14f\"H\x00R\x16organizationExternalId\x88\x01\x01B\x1b\n" +
	"\x19_organization_external_id\"\x85\x01\n" +
	"\x14GetAuthStateResponse\x12:\n" +
	"\n" +
	"auth_state\x18\x01 \x01(\x0e2\x1b.scalekit.v1.auth.AuthStateR\tauthState\x121\n" +
	"\x04user\x18\x02 \x01(\v2\x1d.scalekit.v1.auth.UserDetailsR\x04user\"\x8c\x01\n" +
	"\x13GetAuthErrorRequest\x12u\n" +
	"\berror_id\x18\x01 \x01(\tBZ\x92AH2.Unique identifier for the authentication errorJ\x16\"err_1234567890abcdef\"\xbaH\fr\n" +
	"\x10\x01\x18@:\x04err_R\aerrorId\"Y\n" +
	"\x14GetAuthErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12+\n" +
	"\x11error_description\x18\x02 \x01(\tR\x10errorDescription*:\n" +
	"\x06Intent\x12\x16\n" +
	"\x12INTENT_UNSPECIFIED\x10\x00\x12\v\n" +
	"\asign_in\x10\x01\x12\v\n" +
	"\asign_up\x10\x02*\xb4\x04\n" +
	"\tAuthState\x12\x1a\n" +
	"\x16AUTH_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aAUTHENTICATION_IN_PROGRESS\x10\x01\x12\x19\n" +
	"\x15ORGANIZATION_SWITCHER\x10\x02\x12\x19\n" +
	"\x15ORGANIZATION_SELECTED\x10\x03\x12\x17\n" +
	"\x13ORGANIZATION_SIGNUP\x10\x04\x12 \n" +
	"\x1cORGANIZATION_SWITCHER_SIGNUP\x10\x05\x12\x1c\n" +
	"\x18OTP_VERIFICATION_PENDING\x10\x06\x12\x13\n" +
	"\x0fMAGIC_LINK_SENT\x10\a\x12&\n" +
	"\"LINK_SENT_OTP_VERIFICATION_PENDING\x10\b\x12\x10\n" +
	"\fOTP_VERIFIED\x10\t\x12\x11\n" +
	"\rLINK_VERIFIED\x10\n" +
	"\x12\x15\n" +
	"\x11SSO_AUTHENTICATED\x10\v\x12\x14\n" +
	"\x10ORG_USER_CREATED\x10\f\x12\x1c\n" +
	"\x18AUTHENTICATION_COMPLETED\x10\r\x12\x19\n" +
	"\x15AUTHENTICATION_FAILED\x10\x0e\x12\x15\n" +
	"\x11WEBAUTHN_VERIFIED\x10\x0f\x12 \n" +
	"\x1cVERIFICATION_MAGIC_LINK_SENT\x10\x10\x12$\n" +
	" VERIFICATION_MAGIC_LINK_OTP_SENT\x10\x11\x12\x19\n" +
	"\x15VERIFICATION_OTP_SENT\x10\x12\x12\x1a\n" +
	"\x16VERIFICATION_COMPLETED\x10\x132\xa7\x10\n" +
	"\vAuthService\x12\x98\x01\n" +
	"\x0fListAuthMethods\x12(.scalekit.v1.auth.ListAuthMethodsRequest\x1a).scalekit.v1.auth.ListAuthMethodsResponse\"0\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/authmethods\x12\xba\x01\n" +
	"\x13DiscoveryAuthMethod\x12,.scalekit.v1.auth.DiscoveryAuthMethodRequest\x1a-.scalekit.v1.auth.DiscoveryAuthMethodResponse\"F\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02+:\x11discovery_request\"\x16/api/v1/auth:discovery\x12\xc0\x01\n" +
	"\x15VerifyPasswordLessOtp\x12..scalekit.v1.auth.VerifyPasswordLessOtpRequest\x1a/.scalekit.v1.auth.VerifyPasswordLessOtpResponse\"F\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02+:\aotp_req\" /api/v1/auth/passwordless:verify\x12\x83\x01\n" +
	"\x12ResendPasswordless\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"=\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02\"\" /api/v1/auth/passwordless:resend\x12\x99\x01\n" +
	"\x15ListUserOrganizations\x12\x16.google.protobuf.Empty\x1a/.scalekit.v1.auth.ListUserOrganizationsResponse\"7\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/auth:organizations\x12\xa4\x01\n" +
	"\x12SignupOrganization\x12+.scalekit.v1.auth.SignupOrganizationRequest\x1a,.scalekit.v1.auth.SignupOrganizationResponse\"3\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth:signup\x12\x7f\n" +
	"\fGetAuthState\x12\x16.google.protobuf.Empty\x1a&.scalekit.v1.auth.GetAuthStateResponse\"/\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/auth/state\x12\xb6\x01\n" +
	"\fGetAuthError\x12%.scalekit.v1.auth.GetAuthErrorRequest\x1a&.scalekit.v1.auth.GetAuthErrorResponse\"W\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02<Z\x1f\x12\x1d/api/v1/auth/error/{error_id}\x12\x19/api/v1/errors/{error_id}\x12j\n" +
	"\x06Logout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"0\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02\x15\"\x13/api/v1/auth/logout\x12\xb2\x01\n" +
	"\x15GetAuthCustomizations\x12..scalekit.v1.auth.GetAuthCustomizationsRequest\x1a/.scalekit.v1.auth.GetAuthCustomizationsResponse\"8\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/auth:customizations\x12\x88\x01\n" +
	"\x0fGetAuthFeatures\x12\x16.google.protobuf.Empty\x1a).scalekit.v1.auth.GetAuthFeaturesResponse\"2\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/auth:features\x12\xcd\x02\n" +
	"\x16UpdateLoginUserDetails\x12/.scalekit.v1.auth.UpdateLoginUserDetailsRequest\x1a\x16.google.protobuf.Empty\"\xe9\x01\x92Az\n" +
	"\vConnections\x12%Update User Details for login request\x1a%Update User Details for login requestJ\x1d\n" +
	"\x03200\x12\x16\n" +
	"\x14Deleted Successfully\x82\xb5\x18\x02\x18\x04\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02Q:\x04user\"I/api/v1/connections/{connection_id}/auth-requests/{login_request_id}/userB\xc9\x01\n" +
	"\x14com.scalekit.v1.authB\tAuthProtoP\x01ZDgithub.com/scalekit-inc/scalekit-sdk-go/v2/pkg/grpc/scalekit/v1/auth\xa2\x02\x03SVA\xaa\x02\x10Scalekit.V1.Auth\xca\x02\x10Scalekit\\V1\\Auth\xe2\x02\x1cScalekit\\V1\\Auth\\GPBMetadata\xea\x02\x12Scalekit::V1::Authb\x06proto3"

var (
	file_scalekit_v1_auth_auth_proto_rawDescOnce sync.Once
	file_scalekit_v1_auth_auth_proto_rawDescData []byte
)

func file_scalekit_v1_auth_auth_proto_rawDescGZIP() []byte {
	file_scalekit_v1_auth_auth_proto_rawDescOnce.Do(func() {
		file_scalekit_v1_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scalekit_v1_auth_auth_proto_rawDesc), len(file_scalekit_v1_auth_auth_proto_rawDesc)))
	})
	return file_scalekit_v1_auth_auth_proto_rawDescData
}

var file_scalekit_v1_auth_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_scalekit_v1_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_scalekit_v1_auth_auth_proto_goTypes = []any{
	(Intent)(0),                           // 0: scalekit.v1.auth.Intent
	(AuthState)(0),                        // 1: scalekit.v1.auth.AuthState
	(*ListAuthMethodsRequest)(nil),        // 2: scalekit.v1.auth.ListAuthMethodsRequest
	(*ListAuthMethodsResponse)(nil),       // 3: scalekit.v1.auth.ListAuthMethodsResponse
	(*AuthMethod)(nil),                    // 4: scalekit.v1.auth.AuthMethod
	(*DiscoveryAuthMethodRequest)(nil),    // 5: scalekit.v1.auth.DiscoveryAuthMethodRequest
	(*DiscoveryRequest)(nil),              // 6: scalekit.v1.auth.DiscoveryRequest
	(*DiscoveryAuthMethodResponse)(nil),   // 7: scalekit.v1.auth.DiscoveryAuthMethodResponse
	(*GetAuthCustomizationsRequest)(nil),  // 8: scalekit.v1.auth.GetAuthCustomizationsRequest
	(*PortalSettings)(nil),                // 9: scalekit.v1.auth.PortalSettings
	(*GetAuthCustomizationsResponse)(nil), // 10: scalekit.v1.auth.GetAuthCustomizationsResponse
	(*GetAuthFeaturesResponse)(nil),       // 11: scalekit.v1.auth.GetAuthFeaturesResponse
	(*VerifyPasswordLessOtpRequest)(nil),  // 12: scalekit.v1.auth.VerifyPasswordLessOtpRequest
	(*VerifyPasswordLessOtpResponse)(nil), // 13: scalekit.v1.auth.VerifyPasswordLessOtpResponse
	(*OTPRequest)(nil),                    // 14: scalekit.v1.auth.OTPRequest
	(*ListUserOrganizationsResponse)(nil), // 15: scalekit.v1.auth.ListUserOrganizationsResponse
	(*Organization)(nil),                  // 16: scalekit.v1.auth.Organization
	(*UserDetails)(nil),                   // 17: scalekit.v1.auth.UserDetails
	(*SignupOrganizationRequest)(nil),     // 18: scalekit.v1.auth.SignupOrganizationRequest
	(*SignupOrganizationResponse)(nil),    // 19: scalekit.v1.auth.SignupOrganizationResponse
	(*UpdateLoginUserDetailsRequest)(nil), // 20: scalekit.v1.auth.UpdateLoginUserDetailsRequest
	(*User)(nil),                          // 21: scalekit.v1.auth.User
	(*GetAuthStateResponse)(nil),          // 22: scalekit.v1.auth.GetAuthStateResponse
	(*GetAuthErrorRequest)(nil),           // 23: scalekit.v1.auth.GetAuthErrorRequest
	(*GetAuthErrorResponse)(nil),          // 24: scalekit.v1.auth.GetAuthErrorResponse
	(connections.ConnectionType)(0),       // 25: scalekit.v1.connections.ConnectionType
	(connections.PasswordlessType)(0),     // 26: scalekit.v1.connections.PasswordlessType
	(*structpb.Struct)(nil),               // 27: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),         // 28: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 29: google.protobuf.Empty
}
var file_scalekit_v1_auth_auth_proto_depIdxs = []int32{
	4,  // 0: scalekit.v1.auth.ListAuthMethodsResponse.auth_methods:type_name -> scalekit.v1.auth.AuthMethod
	25, // 1: scalekit.v1.auth.AuthMethod.connection_type:type_name -> scalekit.v1.connections.ConnectionType
	26, // 2: scalekit.v1.auth.AuthMethod.passwordless_type:type_name -> scalekit.v1.connections.PasswordlessType
	6,  // 3: scalekit.v1.auth.DiscoveryAuthMethodRequest.discovery_request:type_name -> scalekit.v1.auth.DiscoveryRequest
	0,  // 4: scalekit.v1.auth.DiscoveryRequest.intent:type_name -> scalekit.v1.auth.Intent
	4,  // 5: scalekit.v1.auth.DiscoveryAuthMethodResponse.auth_method:type_name -> scalekit.v1.auth.AuthMethod
	27, // 6: scalekit.v1.auth.GetAuthCustomizationsResponse.customization_settings:type_name -> google.protobuf.Struct
	9,  // 7: scalekit.v1.auth.GetAuthCustomizationsResponse.settings:type_name -> scalekit.v1.auth.PortalSettings
	27, // 8: scalekit.v1.auth.GetAuthFeaturesResponse.features:type_name -> google.protobuf.Struct
	14, // 9: scalekit.v1.auth.VerifyPasswordLessOtpRequest.otp_req:type_name -> scalekit.v1.auth.OTPRequest
	16, // 10: scalekit.v1.auth.ListUserOrganizationsResponse.organizations:type_name -> scalekit.v1.auth.Organization
	17, // 11: scalekit.v1.auth.ListUserOrganizationsResponse.user:type_name -> scalekit.v1.auth.UserDetails
	0,  // 12: scalekit.v1.auth.ListUserOrganizationsResponse.intent:type_name -> scalekit.v1.auth.Intent
	28, // 13: scalekit.v1.auth.Organization.invitation_accepted_at:type_name -> google.protobuf.Timestamp
	28, // 14: scalekit.v1.auth.Organization.invitation_created_at:type_name -> google.protobuf.Timestamp
	28, // 15: scalekit.v1.auth.Organization.invitation_expires_at:type_name -> google.protobuf.Timestamp
	21, // 16: scalekit.v1.auth.UpdateLoginUserDetailsRequest.user:type_name -> scalekit.v1.auth.User
	27, // 17: scalekit.v1.auth.User.custom_attributes:type_name -> google.protobuf.Struct
	1,  // 18: scalekit.v1.auth.GetAuthStateResponse.auth_state:type_name -> scalekit.v1.auth.AuthState
	17, // 19: scalekit.v1.auth.GetAuthStateResponse.user:type_name -> scalekit.v1.auth.UserDetails
	2,  // 20: scalekit.v1.auth.AuthService.ListAuthMethods:input_type -> scalekit.v1.auth.ListAuthMethodsRequest
	5,  // 21: scalekit.v1.auth.AuthService.DiscoveryAuthMethod:input_type -> scalekit.v1.auth.DiscoveryAuthMethodRequest
	12, // 22: scalekit.v1.auth.AuthService.VerifyPasswordLessOtp:input_type -> scalekit.v1.auth.VerifyPasswordLessOtpRequest
	29, // 23: scalekit.v1.auth.AuthService.ResendPasswordless:input_type -> google.protobuf.Empty
	29, // 24: scalekit.v1.auth.AuthService.ListUserOrganizations:input_type -> google.protobuf.Empty
	18, // 25: scalekit.v1.auth.AuthService.SignupOrganization:input_type -> scalekit.v1.auth.SignupOrganizationRequest
	29, // 26: scalekit.v1.auth.AuthService.GetAuthState:input_type -> google.protobuf.Empty
	23, // 27: scalekit.v1.auth.AuthService.GetAuthError:input_type -> scalekit.v1.auth.GetAuthErrorRequest
	29, // 28: scalekit.v1.auth.AuthService.Logout:input_type -> google.protobuf.Empty
	8,  // 29: scalekit.v1.auth.AuthService.GetAuthCustomizations:input_type -> scalekit.v1.auth.GetAuthCustomizationsRequest
	29, // 30: scalekit.v1.auth.AuthService.GetAuthFeatures:input_type -> google.protobuf.Empty
	20, // 31: scalekit.v1.auth.AuthService.UpdateLoginUserDetails:input_type -> scalekit.v1.auth.UpdateLoginUserDetailsRequest
	3,  // 32: scalekit.v1.auth.AuthService.ListAuthMethods:output_type -> scalekit.v1.auth.ListAuthMethodsResponse
	7,  // 33: scalekit.v1.auth.AuthService.DiscoveryAuthMethod:output_type -> scalekit.v1.auth.DiscoveryAuthMethodResponse
	13, // 34: scalekit.v1.auth.AuthService.VerifyPasswordLessOtp:output_type -> scalekit.v1.auth.VerifyPasswordLessOtpResponse
	29, // 35: scalekit.v1.auth.AuthService.ResendPasswordless:output_type -> google.protobuf.Empty
	15, // 36: scalekit.v1.auth.AuthService.ListUserOrganizations:output_type -> scalekit.v1.auth.ListUserOrganizationsResponse
	19, // 37: scalekit.v1.auth.AuthService.SignupOrganization:output_type -> scalekit.v1.auth.SignupOrganizationResponse
	22, // 38: scalekit.v1.auth.AuthService.GetAuthState:output_type -> scalekit.v1.auth.GetAuthStateResponse
	24, // 39: scalekit.v1.auth.AuthService.GetAuthError:output_type -> scalekit.v1.auth.GetAuthErrorResponse
	29, // 40: scalekit.v1.auth.AuthService.Logout:output_type -> google.protobuf.Empty
	10, // 41: scalekit.v1.auth.AuthService.GetAuthCustomizations:output_type -> scalekit.v1.auth.GetAuthCustomizationsResponse
	11, // 42: scalekit.v1.auth.AuthService.GetAuthFeatures:output_type -> scalekit.v1.auth.GetAuthFeaturesResponse
	29, // 43: scalekit.v1.auth.AuthService.UpdateLoginUserDetails:output_type -> google.protobuf.Empty
	32, // [32:44] is the sub-list for method output_type
	20, // [20:32] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_scalekit_v1_auth_auth_proto_init() }
func file_scalekit_v1_auth_auth_proto_init() {
	if File_scalekit_v1_auth_auth_proto != nil {
		return
	}
	file_scalekit_v1_auth_auth_proto_msgTypes[2].OneofWrappers = []any{}
	file_scalekit_v1_auth_auth_proto_msgTypes[14].OneofWrappers = []any{}
	file_scalekit_v1_auth_auth_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scalekit_v1_auth_auth_proto_rawDesc), len(file_scalekit_v1_auth_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scalekit_v1_auth_auth_proto_goTypes,
		DependencyIndexes: file_scalekit_v1_auth_auth_proto_depIdxs,
		EnumInfos:         file_scalekit_v1_auth_auth_proto_enumTypes,
		MessageInfos:      file_scalekit_v1_auth_auth_proto_msgTypes,
	}.Build()
	File_scalekit_v1_auth_auth_proto = out.File
	file_scalekit_v1_auth_auth_proto_goTypes = nil
	file_scalekit_v1_auth_auth_proto_depIdxs = nil
}
