// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scalekit/v1/auth/webauthn.proto

package auth

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/scalekit-inc/scalekit-sdk-go/v2/pkg/grpc/scalekit/v1/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRegistrationRequest) Reset() {
	*x = BeginRegistrationRequest{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRegistrationRequest) ProtoMessage() {}

func (x *BeginRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRegistrationRequest.ProtoReflect.Descriptor instead.
func (*BeginRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{0}
}

type BeginRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *structpb.Struct       `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRegistrationResponse) Reset() {
	*x = BeginRegistrationResponse{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRegistrationResponse) ProtoMessage() {}

func (x *BeginRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRegistrationResponse.ProtoReflect.Descriptor instead.
func (*BeginRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{1}
}

func (x *BeginRegistrationResponse) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

type FinishRegistrationRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	CredentialId            []byte                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	AttestationObject       []byte                 `protobuf:"bytes,2,opt,name=attestation_object,json=attestationObject,proto3" json:"attestation_object,omitempty"`
	ClientDataJson          []byte                 `protobuf:"bytes,3,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`
	Type                    string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Transports              []string               `protobuf:"bytes,5,rep,name=transports,proto3" json:"transports,omitempty"`
	AuthenticatorAttachment string                 `protobuf:"bytes,6,opt,name=authenticator_attachment,json=authenticatorAttachment,proto3" json:"authenticator_attachment,omitempty"`
	ClientExtensionResults  *structpb.Struct       `protobuf:"bytes,7,opt,name=client_extension_results,json=clientExtensionResults,proto3" json:"client_extension_results,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *FinishRegistrationRequest) Reset() {
	*x = FinishRegistrationRequest{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationRequest) ProtoMessage() {}

func (x *FinishRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationRequest.ProtoReflect.Descriptor instead.
func (*FinishRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{2}
}

func (x *FinishRegistrationRequest) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *FinishRegistrationRequest) GetAttestationObject() []byte {
	if x != nil {
		return x.AttestationObject
	}
	return nil
}

func (x *FinishRegistrationRequest) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

func (x *FinishRegistrationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FinishRegistrationRequest) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *FinishRegistrationRequest) GetAuthenticatorAttachment() string {
	if x != nil {
		return x.AuthenticatorAttachment
	}
	return ""
}

func (x *FinishRegistrationRequest) GetClientExtensionResults() *structpb.Struct {
	if x != nil {
		return x.ClientExtensionResults
	}
	return nil
}

type FinishRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishRegistrationResponse) Reset() {
	*x = FinishRegistrationResponse{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegistrationResponse) ProtoMessage() {}

func (x *FinishRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegistrationResponse.ProtoReflect.Descriptor instead.
func (*FinishRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{3}
}

func (x *FinishRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BeginAuthenticationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *string                `protobuf:"bytes,1,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginAuthenticationRequest) Reset() {
	*x = BeginAuthenticationRequest{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginAuthenticationRequest) ProtoMessage() {}

func (x *BeginAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*BeginAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{4}
}

func (x *BeginAuthenticationRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type BeginAuthenticationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Options       *structpb.Struct       `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginAuthenticationResponse) Reset() {
	*x = BeginAuthenticationResponse{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginAuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginAuthenticationResponse) ProtoMessage() {}

func (x *BeginAuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginAuthenticationResponse.ProtoReflect.Descriptor instead.
func (*BeginAuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{5}
}

func (x *BeginAuthenticationResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BeginAuthenticationResponse) GetOptions() *structpb.Struct {
	if x != nil {
		return x.Options
	}
	return nil
}

type FinishAuthenticationRequest struct {
	state                   protoimpl.MessageState          `protogen:"open.v1"`
	SessionId               string                          `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CredentialId            []byte                          `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	ClientExtensionResults  *structpb.Struct                `protobuf:"bytes,3,opt,name=client_extension_results,json=clientExtensionResults,proto3" json:"client_extension_results,omitempty"`
	Type                    string                          `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Response                *AuthenticatorAssertionResponse `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	AuthenticatorAttachment string                          `protobuf:"bytes,6,opt,name=authenticator_attachment,json=authenticatorAttachment,proto3" json:"authenticator_attachment,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *FinishAuthenticationRequest) Reset() {
	*x = FinishAuthenticationRequest{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishAuthenticationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishAuthenticationRequest) ProtoMessage() {}

func (x *FinishAuthenticationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishAuthenticationRequest.ProtoReflect.Descriptor instead.
func (*FinishAuthenticationRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{6}
}

func (x *FinishAuthenticationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FinishAuthenticationRequest) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *FinishAuthenticationRequest) GetClientExtensionResults() *structpb.Struct {
	if x != nil {
		return x.ClientExtensionResults
	}
	return nil
}

func (x *FinishAuthenticationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FinishAuthenticationRequest) GetResponse() *AuthenticatorAssertionResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FinishAuthenticationRequest) GetAuthenticatorAttachment() string {
	if x != nil {
		return x.AuthenticatorAttachment
	}
	return ""
}

type AuthenticatorAssertionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuthenticatorData []byte                 `protobuf:"bytes,1,opt,name=authenticator_data,json=authenticatorData,proto3" json:"authenticator_data,omitempty"`
	ClientDataJson    []byte                 `protobuf:"bytes,2,opt,name=client_data_json,json=clientDataJson,proto3" json:"client_data_json,omitempty"`
	Signature         []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	UserHandle        []byte                 `protobuf:"bytes,4,opt,name=user_handle,json=userHandle,proto3" json:"user_handle,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthenticatorAssertionResponse) Reset() {
	*x = AuthenticatorAssertionResponse{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticatorAssertionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticatorAssertionResponse) ProtoMessage() {}

func (x *AuthenticatorAssertionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticatorAssertionResponse.ProtoReflect.Descriptor instead.
func (*AuthenticatorAssertionResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{7}
}

func (x *AuthenticatorAssertionResponse) GetAuthenticatorData() []byte {
	if x != nil {
		return x.AuthenticatorData
	}
	return nil
}

func (x *AuthenticatorAssertionResponse) GetClientDataJson() []byte {
	if x != nil {
		return x.ClientDataJson
	}
	return nil
}

func (x *AuthenticatorAssertionResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuthenticatorAssertionResponse) GetUserHandle() []byte {
	if x != nil {
		return x.UserHandle
	}
	return nil
}

type FinishAuthenticationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishAuthenticationResponse) Reset() {
	*x = FinishAuthenticationResponse{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishAuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishAuthenticationResponse) ProtoMessage() {}

func (x *FinishAuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishAuthenticationResponse.ProtoReflect.Descriptor instead.
func (*FinishAuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{8}
}

func (x *FinishAuthenticationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FinishAuthenticationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FinishAuthenticationResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type WebAuthnConfiguration struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RpId                    string                 `protobuf:"bytes,1,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	RpOrigin                string                 `protobuf:"bytes,2,opt,name=rp_origin,json=rpOrigin,proto3" json:"rp_origin,omitempty"`
	UserVerification        string                 `protobuf:"bytes,3,opt,name=user_verification,json=userVerification,proto3" json:"user_verification,omitempty"`
	AuthenticatorAttachment string                 `protobuf:"bytes,4,opt,name=authenticator_attachment,json=authenticatorAttachment,proto3" json:"authenticator_attachment,omitempty"`
	ResidentKey             string                 `protobuf:"bytes,5,opt,name=resident_key,json=residentKey,proto3" json:"resident_key,omitempty"`
	Timeout                 int64                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	AllowedTransports       []string               `protobuf:"bytes,7,rep,name=allowed_transports,json=allowedTransports,proto3" json:"allowed_transports,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *WebAuthnConfiguration) Reset() {
	*x = WebAuthnConfiguration{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthnConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthnConfiguration) ProtoMessage() {}

func (x *WebAuthnConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthnConfiguration.ProtoReflect.Descriptor instead.
func (*WebAuthnConfiguration) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{9}
}

func (x *WebAuthnConfiguration) GetRpId() string {
	if x != nil {
		return x.RpId
	}
	return ""
}

func (x *WebAuthnConfiguration) GetRpOrigin() string {
	if x != nil {
		return x.RpOrigin
	}
	return ""
}

func (x *WebAuthnConfiguration) GetUserVerification() string {
	if x != nil {
		return x.UserVerification
	}
	return ""
}

func (x *WebAuthnConfiguration) GetAuthenticatorAttachment() string {
	if x != nil {
		return x.AuthenticatorAttachment
	}
	return ""
}

func (x *WebAuthnConfiguration) GetResidentKey() string {
	if x != nil {
		return x.ResidentKey
	}
	return ""
}

func (x *WebAuthnConfiguration) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *WebAuthnConfiguration) GetAllowedTransports() []string {
	if x != nil {
		return x.AllowedTransports
	}
	return nil
}

type ListCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCredentialsRequest) Reset() {
	*x = ListCredentialsRequest{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialsRequest) ProtoMessage() {}

func (x *ListCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ListCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{10}
}

func (x *ListCredentialsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListCredentialsResponse struct {
	state                         protoimpl.MessageState         `protogen:"open.v1"`
	Credentials                   []*WebAuthnCredential          `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	AllAcceptedCredentialsOptions *AllAcceptedCredentialsOptions `protobuf:"bytes,2,opt,name=all_accepted_credentials_options,json=allAcceptedCredentialsOptions,proto3" json:"all_accepted_credentials_options,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ListCredentialsResponse) Reset() {
	*x = ListCredentialsResponse{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCredentialsResponse) ProtoMessage() {}

func (x *ListCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ListCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{11}
}

func (x *ListCredentialsResponse) GetCredentials() []*WebAuthnCredential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ListCredentialsResponse) GetAllAcceptedCredentialsOptions() *AllAcceptedCredentialsOptions {
	if x != nil {
		return x.AllAcceptedCredentialsOptions
	}
	return nil
}

type DeleteCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCredentialRequest) Reset() {
	*x = DeleteCredentialRequest{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialRequest) ProtoMessage() {}

func (x *DeleteCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteCredentialRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCredentialRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

type DeleteCredentialResponse struct {
	state                    protoimpl.MessageState    `protogen:"open.v1"`
	Success                  bool                      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UnknownCredentialOptions *UnknownCredentialOptions `protobuf:"bytes,2,opt,name=unknown_credential_options,json=unknownCredentialOptions,proto3" json:"unknown_credential_options,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DeleteCredentialResponse) Reset() {
	*x = DeleteCredentialResponse{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCredentialResponse) ProtoMessage() {}

func (x *DeleteCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCredentialResponse.ProtoReflect.Descriptor instead.
func (*DeleteCredentialResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCredentialResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCredentialResponse) GetUnknownCredentialOptions() *UnknownCredentialOptions {
	if x != nil {
		return x.UnknownCredentialOptions
	}
	return nil
}

type UnknownCredentialOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpId          string                 `protobuf:"bytes,1,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	CredentialId  string                 `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnknownCredentialOptions) Reset() {
	*x = UnknownCredentialOptions{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnknownCredentialOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnknownCredentialOptions) ProtoMessage() {}

func (x *UnknownCredentialOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnknownCredentialOptions.ProtoReflect.Descriptor instead.
func (*UnknownCredentialOptions) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{14}
}

func (x *UnknownCredentialOptions) GetRpId() string {
	if x != nil {
		return x.RpId
	}
	return ""
}

func (x *UnknownCredentialOptions) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

type AllAcceptedCredentialsOptions struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RpId                     string                 `protobuf:"bytes,1,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	UserId                   string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AllAcceptedCredentialIds []string               `protobuf:"bytes,3,rep,name=all_accepted_credential_ids,json=allAcceptedCredentialIds,proto3" json:"all_accepted_credential_ids,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AllAcceptedCredentialsOptions) Reset() {
	*x = AllAcceptedCredentialsOptions{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllAcceptedCredentialsOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllAcceptedCredentialsOptions) ProtoMessage() {}

func (x *AllAcceptedCredentialsOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllAcceptedCredentialsOptions.ProtoReflect.Descriptor instead.
func (*AllAcceptedCredentialsOptions) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{15}
}

func (x *AllAcceptedCredentialsOptions) GetRpId() string {
	if x != nil {
		return x.RpId
	}
	return ""
}

func (x *AllAcceptedCredentialsOptions) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AllAcceptedCredentialsOptions) GetAllAcceptedCredentialIds() []string {
	if x != nil {
		return x.AllAcceptedCredentialIds
	}
	return nil
}

type UpdateCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCredentialRequest) Reset() {
	*x = UpdateCredentialRequest{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCredentialRequest) ProtoMessage() {}

func (x *UpdateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCredentialRequest.ProtoReflect.Descriptor instead.
func (*UpdateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCredentialRequest) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

func (x *UpdateCredentialRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type UpdateCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *WebAuthnCredential    `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCredentialResponse) Reset() {
	*x = UpdateCredentialResponse{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCredentialResponse) ProtoMessage() {}

func (x *UpdateCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCredentialResponse.ProtoReflect.Descriptor instead.
func (*UpdateCredentialResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateCredentialResponse) GetCredential() *WebAuthnCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type WebAuthnCredential struct {
	state              protoimpl.MessageState                 `protogen:"open.v1"`
	Id                 string                                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CredentialId       []byte                                 `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	AttestationType    string                                 `protobuf:"bytes,4,opt,name=attestation_type,json=attestationType,proto3" json:"attestation_type,omitempty"`
	Authenticator      *WebAuthnCredential_Authenticator      `protobuf:"bytes,5,opt,name=authenticator,proto3" json:"authenticator,omitempty"`
	Transports         []string                               `protobuf:"bytes,6,rep,name=transports,proto3" json:"transports,omitempty"`
	AuthenticatorFlags *WebAuthnCredential_AuthenticatorFlags `protobuf:"bytes,7,opt,name=authenticator_flags,json=authenticatorFlags,proto3" json:"authenticator_flags,omitempty"`
	CreatedAt          *timestamppb.Timestamp                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserAgent          *WebAuthnCredential_UserAgent          `protobuf:"bytes,10,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	ClientInfo         *WebAuthnCredential_ClientInfo         `protobuf:"bytes,11,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
	DisplayName        *string                                `protobuf:"bytes,12,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WebAuthnCredential) Reset() {
	*x = WebAuthnCredential{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthnCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthnCredential) ProtoMessage() {}

func (x *WebAuthnCredential) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthnCredential.ProtoReflect.Descriptor instead.
func (*WebAuthnCredential) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{18}
}

func (x *WebAuthnCredential) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebAuthnCredential) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WebAuthnCredential) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *WebAuthnCredential) GetAttestationType() string {
	if x != nil {
		return x.AttestationType
	}
	return ""
}

func (x *WebAuthnCredential) GetAuthenticator() *WebAuthnCredential_Authenticator {
	if x != nil {
		return x.Authenticator
	}
	return nil
}

func (x *WebAuthnCredential) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *WebAuthnCredential) GetAuthenticatorFlags() *WebAuthnCredential_AuthenticatorFlags {
	if x != nil {
		return x.AuthenticatorFlags
	}
	return nil
}

func (x *WebAuthnCredential) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WebAuthnCredential) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WebAuthnCredential) GetUserAgent() *WebAuthnCredential_UserAgent {
	if x != nil {
		return x.UserAgent
	}
	return nil
}

func (x *WebAuthnCredential) GetClientInfo() *WebAuthnCredential_ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

func (x *WebAuthnCredential) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

type GetRelatedOriginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelatedOriginsRequest) Reset() {
	*x = GetRelatedOriginsRequest{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelatedOriginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelatedOriginsRequest) ProtoMessage() {}

func (x *GetRelatedOriginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelatedOriginsRequest.ProtoReflect.Descriptor instead.
func (*GetRelatedOriginsRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{19}
}

type GetRelatedOriginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Origins       []string               `protobuf:"bytes,1,rep,name=origins,proto3" json:"origins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelatedOriginsResponse) Reset() {
	*x = GetRelatedOriginsResponse{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelatedOriginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelatedOriginsResponse) ProtoMessage() {}

func (x *GetRelatedOriginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelatedOriginsResponse.ProtoReflect.Descriptor instead.
func (*GetRelatedOriginsResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{20}
}

func (x *GetRelatedOriginsResponse) GetOrigins() []string {
	if x != nil {
		return x.Origins
	}
	return nil
}

type WebAuthnCredential_AuthenticatorFlags struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserPresent    bool                   `protobuf:"varint,1,opt,name=user_present,json=userPresent,proto3" json:"user_present,omitempty"`
	UserVerified   bool                   `protobuf:"varint,2,opt,name=user_verified,json=userVerified,proto3" json:"user_verified,omitempty"`
	BackupEligible bool                   `protobuf:"varint,3,opt,name=backup_eligible,json=backupEligible,proto3" json:"backup_eligible,omitempty"`
	BackupState    bool                   `protobuf:"varint,4,opt,name=backup_state,json=backupState,proto3" json:"backup_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebAuthnCredential_AuthenticatorFlags) Reset() {
	*x = WebAuthnCredential_AuthenticatorFlags{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthnCredential_AuthenticatorFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthnCredential_AuthenticatorFlags) ProtoMessage() {}

func (x *WebAuthnCredential_AuthenticatorFlags) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthnCredential_AuthenticatorFlags.ProtoReflect.Descriptor instead.
func (*WebAuthnCredential_AuthenticatorFlags) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{18, 0}
}

func (x *WebAuthnCredential_AuthenticatorFlags) GetUserPresent() bool {
	if x != nil {
		return x.UserPresent
	}
	return false
}

func (x *WebAuthnCredential_AuthenticatorFlags) GetUserVerified() bool {
	if x != nil {
		return x.UserVerified
	}
	return false
}

func (x *WebAuthnCredential_AuthenticatorFlags) GetBackupEligible() bool {
	if x != nil {
		return x.BackupEligible
	}
	return false
}

func (x *WebAuthnCredential_AuthenticatorFlags) GetBackupState() bool {
	if x != nil {
		return x.BackupState
	}
	return false
}

type WebAuthnCredential_Authenticator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aaguid        string                 `protobuf:"bytes,1,opt,name=aaguid,proto3" json:"aaguid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Attachment    string                 `protobuf:"bytes,3,opt,name=attachment,proto3" json:"attachment,omitempty"`
	IconDark      string                 `protobuf:"bytes,4,opt,name=icon_dark,json=iconDark,proto3" json:"icon_dark,omitempty"`
	IconLight     string                 `protobuf:"bytes,5,opt,name=icon_light,json=iconLight,proto3" json:"icon_light,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAuthnCredential_Authenticator) Reset() {
	*x = WebAuthnCredential_Authenticator{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthnCredential_Authenticator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthnCredential_Authenticator) ProtoMessage() {}

func (x *WebAuthnCredential_Authenticator) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthnCredential_Authenticator.ProtoReflect.Descriptor instead.
func (*WebAuthnCredential_Authenticator) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{18, 1}
}

func (x *WebAuthnCredential_Authenticator) GetAaguid() string {
	if x != nil {
		return x.Aaguid
	}
	return ""
}

func (x *WebAuthnCredential_Authenticator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebAuthnCredential_Authenticator) GetAttachment() string {
	if x != nil {
		return x.Attachment
	}
	return ""
}

func (x *WebAuthnCredential_Authenticator) GetIconDark() string {
	if x != nil {
		return x.IconDark
	}
	return ""
}

func (x *WebAuthnCredential_Authenticator) GetIconLight() string {
	if x != nil {
		return x.IconLight
	}
	return ""
}

type WebAuthnCredential_UserAgent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Raw            string                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Browser        string                 `protobuf:"bytes,3,opt,name=browser,proto3" json:"browser,omitempty"`
	BrowserVersion string                 `protobuf:"bytes,4,opt,name=browser_version,json=browserVersion,proto3" json:"browser_version,omitempty"`
	Os             string                 `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	OsVersion      string                 `protobuf:"bytes,6,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	DeviceType     string                 `protobuf:"bytes,7,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	DeviceModel    string                 `protobuf:"bytes,8,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebAuthnCredential_UserAgent) Reset() {
	*x = WebAuthnCredential_UserAgent{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthnCredential_UserAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthnCredential_UserAgent) ProtoMessage() {}

func (x *WebAuthnCredential_UserAgent) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthnCredential_UserAgent.ProtoReflect.Descriptor instead.
func (*WebAuthnCredential_UserAgent) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{18, 2}
}

func (x *WebAuthnCredential_UserAgent) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *WebAuthnCredential_UserAgent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebAuthnCredential_UserAgent) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *WebAuthnCredential_UserAgent) GetBrowserVersion() string {
	if x != nil {
		return x.BrowserVersion
	}
	return ""
}

func (x *WebAuthnCredential_UserAgent) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *WebAuthnCredential_UserAgent) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *WebAuthnCredential_UserAgent) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *WebAuthnCredential_UserAgent) GetDeviceModel() string {
	if x != nil {
		return x.DeviceModel
	}
	return ""
}

type WebAuthnCredential_ClientInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ip                string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Region            string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	RegionSubdivision string                 `protobuf:"bytes,3,opt,name=region_subdivision,json=regionSubdivision,proto3" json:"region_subdivision,omitempty"`
	City              string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WebAuthnCredential_ClientInfo) Reset() {
	*x = WebAuthnCredential_ClientInfo{}
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthnCredential_ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthnCredential_ClientInfo) ProtoMessage() {}

func (x *WebAuthnCredential_ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auth_webauthn_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthnCredential_ClientInfo.ProtoReflect.Descriptor instead.
func (*WebAuthnCredential_ClientInfo) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auth_webauthn_proto_rawDescGZIP(), []int{18, 3}
}

func (x *WebAuthnCredential_ClientInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *WebAuthnCredential_ClientInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *WebAuthnCredential_ClientInfo) GetRegionSubdivision() string {
	if x != nil {
		return x.RegionSubdivision
	}
	return ""
}

func (x *WebAuthnCredential_ClientInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

var File_scalekit_v1_auth_webauthn_proto protoreflect.FileDescriptor

const file_scalekit_v1_auth_webauthn_proto_rawDesc = "" +
	"\n" +
	"\x1fscalekit/v1/auth/webauthn.proto\x12\x19scalekit.v1.auth.webauthn\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/api/visibility.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a!scalekit/v1/options/options.proto\"\x1a\n" +
	"\x18BeginRegistrationRequest\"\xa5\x01\n" +
	"\x19BeginRegistrationResponse\x12\x87\x01\n" +
	"\aoptions\x18\x01 \x01(\v2\x17.google.protobuf.StructBT\x92AQ2OWebAuthn options including challenge and user information for the authenticatorR\aoptions\"\x89\a\n" +
	"\x19FinishRegistrationRequest\x12o\n" +
	"\rcredential_id\x18\x01 \x01(\fBJ\x92AA2?The unique credential identifier generated by the authenticator\xbaH\x03\xc8\x01\x01R\fcredentialId\x12\x94\x01\n" +
	"\x12attestation_object\x18\x02 \x01(\fBe\x92A\\2ZThe attestation object from the authenticator response, contains the credential public key\xbaH\x03\xc8\x01\x01R\x11attestationObject\x12x\n" +
	"\x10client_data_json\x18\x03 \x01(\fBN\x92AE2CClient-side JSON data from the authenticator, used for verification\xbaH\x03\xc8\x01\x01R\x0eclientDataJson\x12N\n" +
	"\x04type\x18\x04 \x01(\tB:\x92A72'Credential type, typically \"public-key\"J\f\"public-key\"R\x04type\x12e\n" +
	"\n" +
	"transports\x18\x05 \x03(\tBE\x92AB2@Optional transport hints (e.g., \"usb\", \"ble\", \"nfc\", \"internal\")R\n" +
	"transports\x12\x94\x01\n" +
	"\x18authenticator_attachment\x18\x06 \x01(\tBY\x92AV2HAuthenticator attachment type: \"platform\" (built-in) or \"cross-platform\"J\n" +
	"\"platform\"R\x17authenticatorAttachment\x12\x9b\x01\n" +
	"\x18client_extension_results\x18\a \x01(\v2\x17.google.protobuf.StructBH\x92AE2CExtension results from the client, if any extensions were requestedR\x16clientExtensionResults\"u\n" +
	"\x1aFinishRegistrationResponse\x12W\n" +
	"\asuccess\x18\x01 \x01(\bB=\x92A:22Whether the credential was successfully registeredJ\x04trueR\asuccess\"\xaf\x01\n" +
	"\x1aBeginAuthenticationRequest\x12\x86\x01\n" +
	"\x05email\x18\x01 \x01(\tBk\x92Aa2KOptional email to filter registered credentials (enables usernameless flow)J\x12\"user@example.com\"\xbaH\x04r\x02`\x01H\x00R\x05email\x88\x01\x01B\b\n" +
	"\x06_email\"\xa3\x02\n" +
	"\x1bBeginAuthenticationResponse\x12w\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tBX\x92AU2DSession identifier for linking begin and finish authentication callsJ\r\"sess_abc123\"R\tsessionId\x12\x8a\x01\n" +
	"\aoptions\x18\x02 \x01(\v2\x17.google.protobuf.StructBW\x92AT2RWebAuthn options including challenge and allowed credentials for the authenticatorR\aoptions\"\x8a\x06\n" +
	"\x1bFinishAuthenticationRequest\x12m\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tBN\x92AE24Session identifier from the BeginAuthentication callJ\r\"sess_abc123\"\xbaH\x03\xc8\x01\x01R\tsessionId\x12_\n" +
	"\rcredential_id\x18\x02 \x01(\fB:\x92A12/The credential ID being used for authentication\xbaH\x03\xc8\x01\x01R\fcredentialId\x12\x9b\x01\n" +
	"\x18client_extension_results\x18\x03 \x01(\v2\x17.google.protobuf.StructBH\x92AE2CExtension results from the client, if any extensions were requestedR\x16clientExtensionResults\x12N\n" +
	"\x04type\x18\x04 \x01(\tB:\x92A72'Credential type, typically \"public-key\"J\f\"public-key\"R\x04type\x12\x8f\x01\n" +
	"\bresponse\x18\x05 \x01(\v29.scalekit.v1.auth.webauthn.AuthenticatorAssertionResponseB8\x92A/2-The authenticator's response to the challenge\xbaH\x03\xc8\x01\x01R\bresponse\x12\x9a\x01\n" +
	"\x18authenticator_attachment\x18\x06 \x01(\tB_\x92A\\2HAuthenticator attachment type: \"platform\" (built-in) or \"cross-platform\"J\x10\"cross-platform\"R\x17authenticatorAttachment\"\xfe\x03\n" +
	"\x1eAuthenticatorAssertionResponse\x12q\n" +
	"\x12authenticator_data\x18\x01 \x01(\fBB\x92A927Binary data about the authenticator state and signature\xbaH\x03\xc8\x01\x01R\x11authenticatorData\x12z\n" +
	"\x10client_data_json\x18\x02 \x01(\fBP\x92AG2EClient-side JSON data, includes challenge and origin for verification\xbaH\x03\xc8\x01\x01R\x0eclientDataJson\x12w\n" +
	"\tsignature\x18\x03 \x01(\fBY\x92AP2NCryptographic signature of the challenge, proves possession of the private key\xbaH\x03\xc8\x01\x01R\tsignature\x12t\n" +
	"\vuser_handle\x18\x04 \x01(\fBS\x92AJ2HUser ID that authenticated, binds assertion to the registered credential\xbaH\x03\xc8\x01\x01R\n" +
	"userHandle\"\xc4\x02\n" +
	"\x1cFinishAuthenticationResponse\x12N\n" +
	"\asuccess\x18\x01 \x01(\bB4\x92A12)Whether the authentication was successfulJ\x04trueR\asuccess\x12M\n" +
	"\auser_id\x18\x02 \x01(\tB4\x92A12 The ID of the authenticated userJ\r\"user_xyz789\"R\x06userId\x12\x84\x01\n" +
	"\rsession_token\x18\x03 \x01(\tB_\x92A\\2/Session token for establishing the user sessionJ)\"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...\"R\fsessionToken\"\xcd\x06\n" +
	"\x15WebAuthnConfiguration\x12T\n" +
	"\x05rp_id\x18\x01 \x01(\tB?\x92A<2+Relying Party ID, typically the domain nameJ\r\"example.com\"R\x04rpId\x12f\n" +
	"\trp_origin\x18\x02 \x01(\tBI\x92AF2-Origin URL where the credential is registeredJ\x15\"https://example.com\"R\brpOrigin\x12\x87\x01\n" +
	"\x11user_verification\x18\x03 \x01(\tBZ\x92AW2HUser verification requirement: \"required\", \"preferred\", or \"discouraged\"J\v\"preferred\"R\x10userVerification\x12\x9b\x01\n" +
	"\x18authenticator_attachment\x18\x04 \x01(\tB`\x92A]2OPreferred authenticator type: \"platform\", \"cross-platform\", or empty for eitherJ\n" +
	"\"platform\"R\x17authenticatorAttachment\x12x\n" +
	"\fresident_key\x18\x05 \x01(\tBU\x92AR2CResident key requirement: \"required\", \"preferred\", or \"discouraged\"J\v\"preferred\"R\vresidentKey\x12m\n" +
	"\atimeout\x18\x06 \x01(\x03BS\x92AP2GTimeout in milliseconds for the authenticator to complete the operationJ\x0560000R\atimeout\x12e\n" +
	"\x12allowed_transports\x18\a \x03(\tB6\x92A321Allowed transport types the authenticator can useR\x11allowedTransports\"\x8f\x01\n" +
	"\x16ListCredentialsRequest\x12u\n" +
	"\auser_id\x18\x01 \x01(\tB\\\x92AY2HUser ID to list credentials for (optional, current user if not provided)J\r\"user_xyz789\"R\x06userId\"\xea\x02\n" +
	"\x17ListCredentialsResponse\x12z\n" +
	"\vcredentials\x18\x01 \x03(\v2-.scalekit.v1.auth.webauthn.WebAuthnCredentialB)\x92A&2$All passkeys registered for the userR\vcredentials\x12\xd2\x01\n" +
	" all_accepted_credentials_options\x18\x02 \x01(\v28.scalekit.v1.auth.webauthn.AllAcceptedCredentialsOptionsBO\x92AL2JOptions including RP ID and all accepted credential IDs for authenticationR\x1dallAcceptedCredentialsOptions\"u\n" +
	"\x17DeleteCredentialRequest\x12Z\n" +
	"\rcredential_id\x18\x01 \x01(\tB5\x92A,2\x1bThe credential ID to deleteJ\r\"cred_abc123\"\xbaH\x03\xc8\x01\x01R\fcredentialId\"\xaa\x02\n" +
	"\x18DeleteCredentialResponse\x12T\n" +
	"\asuccess\x18\x01 \x01(\bB:\x92A72/Whether the credential was successfully deletedJ\x04trueR\asuccess\x12\xb7\x01\n" +
	"\x1aunknown_credential_options\x18\x02 \x01(\v23.scalekit.v1.auth.webauthn.UnknownCredentialOptionsBD\x92AA2?Options for handling unknown credentials in client applicationsR\x18unknownCredentialOptions\"\xb6\x01\n" +
	"\x18UnknownCredentialOptions\x12F\n" +
	"\x05rp_id\x18\x01 \x01(\tB1\x92A.2\x1dThe RP ID for this credentialJ\r\"example.com\"R\x04rpId\x12R\n" +
	"\rcredential_id\x18\x02 \x01(\tB-\x92A*2\x19The deleted credential IDJ\r\"cred_abc123\"R\fcredentialId\"\xc1\x02\n" +
	"\x1dAllAcceptedCredentialsOptions\x12S\n" +
	"\x05rp_id\x18\x01 \x01(\tB>\x92A;2*Relying Party ID for credential operationsJ\r\"example.com\"R\x04rpId\x12P\n" +
	"\auser_id\x18\x02 \x01(\tB7\x92A42#User ID for credential verificationJ\r\"user_xyz789\"R\x06userId\x12y\n" +
	"\x1ball_accepted_credential_ids\x18\x03 \x03(\tB:\x92A725List of credential IDs the user can authenticate withR\x18allAcceptedCredentialIds\"\xf6\x01\n" +
	"\x17UpdateCredentialRequest\x12Z\n" +
	"\rcredential_id\x18\x01 \x01(\tB5\x92A,2\x1bThe credential ID to updateJ\r\"cred_abc123\"\xbaH\x03\xc8\x01\x01R\fcredentialId\x12\x7f\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\\\x92AP2:Human-friendly name for this credential (1-120 characters)J\x12\"My iPhone 15 Pro\"\xbaH\x06r\x04\x10\x01\x18xR\vdisplayName\"\x9d\x01\n" +
	"\x18UpdateCredentialResponse\x12\x80\x01\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2-.scalekit.v1.auth.webauthn.WebAuthnCredentialB1\x92A.2,The updated credential with new display nameR\n" +
	"credential\"\xb1\x19\n" +
	"\x12WebAuthnCredential\x12@\n" +
	"\x02id\x18\x01 \x01(\tB0\x92A-2\x1cCredential unique identifierJ\r\"cred_abc123\"R\x02id\x12O\n" +
	"\auser_id\x18\x02 \x01(\tB6\x92A32\"User ID this credential belongs toJ\r\"user_xyz789\"R\x06userId\x12_\n" +
	"\rcredential_id\x18\x03 \x01(\fB:\x92A725The actual credential ID bytes from the authenticatorR\fcredentialId\x12n\n" +
	"\x10attestation_type\x18\x04 \x01(\tBC\x92A@24Type of attestation: \"none\", \"indirect\", or \"direct\"J\b\"direct\"R\x0fattestationType\x12\x9a\x01\n" +
	"\rauthenticator\x18\x05 \x01(\v2;.scalekit.v1.auth.webauthn.WebAuthnCredential.AuthenticatorB7\x92A422Authenticator information including model and nameR\rauthenticator\x12M\n" +
	"\n" +
	"transports\x18\x06 \x03(\tB-\x92A*2(Supported transports for this credentialR\n" +
	"transports\x12\xa3\x01\n" +
	"\x13authenticator_flags\x18\a \x01(\v2@.scalekit.v1.auth.webauthn.WebAuthnCredential.AuthenticatorFlagsB0\x92A-2+Flags indicating authenticator capabilitiesR\x12authenticatorFlags\x12\x85\x01\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampBJ\x92AG2)Timestamp when the credential was createdJ\x1a\"2025-02-15T06:23:44.560Z\"R\tcreatedAt\x12t\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB9\x92A62\x18Timestamp of last updateJ\x1a\"2025-02-15T06:23:44.560Z\"R\tupdatedAt\x12\x8d\x01\n" +
	"\n" +
	"user_agent\x18\n" +
	" \x01(\v27.scalekit.v1.auth.webauthn.WebAuthnCredential.UserAgentB5\x92A220Browser and device information from registrationR\tuserAgent\x12\x94\x01\n" +
	"\vclient_info\x18\v \x01(\v28.scalekit.v1.auth.webauthn.WebAuthnCredential.ClientInfoB9\x92A624Geographic and network information from registrationR\n" +
	"clientInfo\x12g\n" +
	"\fdisplay_name\x18\f \x01(\tB?\x92A<2,Optional user-friendly name for this passkeyJ\f\"My Yubikey\"H\x00R\vdisplayName\x88\x01\x01\x1a\x95\x03\n" +
	"\x12AuthenticatorFlags\x12Z\n" +
	"\fuser_present\x18\x01 \x01(\bB7\x92A422Whether the user was present during authenticationR\vuserPresent\x12`\n" +
	"\ruser_verified\x18\x02 \x01(\bB;\x92A826Whether the user was verified (e.g., fingerprint, PIN)R\fuserVerified\x12h\n" +
	"\x0fbackup_eligible\x18\x03 \x01(\bB?\x92A<2:Whether this credential can be backed up to another deviceR\x0ebackupEligible\x12W\n" +
	"\fbackup_state\x18\x04 \x01(\bB4\x92A12/Whether this credential was synced or backed upR\vbackupState\x1a\xc3\x03\n" +
	"\rAuthenticator\x12a\n" +
	"\x06aaguid\x18\x01 \x01(\tBI\x92AF2DAuthenticator Attestation GUID (AAGUID) identifying the device modelR\x06aaguid\x12Y\n" +
	"\x04name\x18\x02 \x01(\tBE\x92AB2.Human-readable name of the authenticator modelJ\x10\"Apple Touch ID\"R\x04name\x12k\n" +
	"\n" +
	"attachment\x18\x03 \x01(\tBK\x92AH2:Attachment type: \"platform\" (built-in) or \"cross-platform\"J\n" +
	"\"platform\"R\n" +
	"attachment\x12A\n" +
	"\ticon_dark\x18\x04 \x01(\tB$\x92A!2\x1fIcon URL for dark theme displayR\biconDark\x12D\n" +
	"\n" +
	"icon_light\x18\x05 \x01(\tB%\x92A\"2 Icon URL for light theme displayR\ticonLight\x1a\xf0\x04\n" +
	"\tUserAgent\x12=\n" +
	"\x03raw\x18\x01 \x01(\tB+\x92A(2&Raw user agent string from the browserR\x03raw\x126\n" +
	"\x03url\x18\x02 \x01(\tB$\x92A!2\x1fParsed user agent URL referenceR\x03url\x12P\n" +
	"\abrowser\x18\x03 \x01(\tB6\x92A32'Browser name (e.g., \"Chrome\", \"Safari\")J\b\"Chrome\"R\abrowser\x12V\n" +
	"\x0fbrowser_version\x18\x04 \x01(\tB-\x92A*2\x16Browser version numberJ\x10\"120.0.6099.129\"R\x0ebrowserVersion\x12L\n" +
	"\x02os\x18\x05 \x01(\tB<\x92A92.Operating system name (e.g., \"Windows\", \"iOS\")J\a\"macOS\"R\x02os\x12D\n" +
	"\n" +
	"os_version\x18\x06 \x01(\tB%\x92A\"2\x18Operating system versionJ\x06\"14.2\"R\tosVersion\x12]\n" +
	"\vdevice_type\x18\a \x01(\tB<\x92A92-Device type: \"desktop\", \"mobile\", or \"tablet\"J\b\"mobile\"R\n" +
	"deviceType\x12O\n" +
	"\fdevice_model\x18\b \x01(\tB,\x92A)2\x19Device model if availableJ\f\"iPhone15,2\"R\vdeviceModel\x1a\xb4\x02\n" +
	"\n" +
	"ClientInfo\x12Q\n" +
	"\x02ip\x18\x01 \x01(\tBA\x92A>2/IP address from which credential was registeredJ\v\"192.0.2.1\"R\x02ip\x12A\n" +
	"\x06region\x18\x02 \x01(\tB)\x92A&2\x1eGeographic region (e.g., \"US\")J\x04\"US\"R\x06region\x12[\n" +
	"\x12region_subdivision\x18\x03 \x01(\tB,\x92A)2!Regional subdivision (e.g., \"CA\")J\x04\"CA\"R\x11regionSubdivision\x123\n" +
	"\x04city\x18\x04 \x01(\tB\x1f\x92A\x1c2\tCity nameJ\x0f\"San Francisco\"R\x04cityB\x0f\n" +
	"\r_display_name\"\x1a\n" +
	"\x18GetRelatedOriginsRequest\"{\n" +
	"\x19GetRelatedOriginsResponse\x12^\n" +
	"\aorigins\x18\x01 \x03(\tBD\x92AA2?List of related origins for cross-origin passkey authenticationR\aorigins2\x8a\x1f\n" +
	"\x0fWebAuthnService\x12\xf2\x03\n" +
	"\x11BeginRegistration\x123.scalekit.v1.auth.webauthn.BeginRegistrationRequest\x1a4.scalekit.v1.auth.webauthn.BeginRegistrationResponse\"\xf1\x02\x92A\xaa\x02\x12\x1aStart passkey registration\x1a\x8c\x01Initiates passkey registration for the current user. Returns a challenge and configuration options to be sent to the client's authenticator.J}\n" +
	"\x03200\x12v\n" +
	":Registration initiated with challenge and WebAuthn options\x128\n" +
	"6\x1a4.scalekit.v1.auth.webauthn.BeginRegistrationResponse\x82\xb5\x18\x02\x18\x14\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/webauthn/registration:begin\x12\xdc\x03\n" +
	"\x12FinishRegistration\x124.scalekit.v1.auth.webauthn.FinishRegistrationRequest\x1a5.scalekit.v1.auth.webauthn.FinishRegistrationResponse\"\xd8\x02\x92A\x90\x02\x12\x1dComplete passkey registration\x1a}Completes passkey registration by validating the authenticator response. Returns success status after storing the credential.Jp\n" +
	"\x03200\x12i\n" +
	",Registration completed and credential stored\x129\n" +
	"7\x1a5.scalekit.v1.auth.webauthn.FinishRegistrationResponse\x82\xb5\x18\x02\x18\x14\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/webauthn/registration:finish\x12\x8b\x04\n" +
	"\x13BeginAuthentication\x125.scalekit.v1.auth.webauthn.BeginAuthenticationRequest\x1a6.scalekit.v1.auth.webauthn.BeginAuthenticationResponse\"\x84\x03\x92A\xbb\x02\x12\x1cStart passkey authentication\x1a\xa0\x01Initiates passkey authentication. Optionally accepts an email to filter registered credentials. Returns a session ID and challenge for the client authenticator.Jx\n" +
	"\x03200\x12q\n" +
	"3Authentication initiated with session and challenge\x12:\n" +
	"8\x1a6.scalekit.v1.auth.webauthn.BeginAuthenticationResponse\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02*:\x01*\"%/api/v1/webauthn/authentication:begin\x12\x8d\x04\n" +
	"\x14FinishAuthentication\x126.scalekit.v1.auth.webauthn.FinishAuthenticationRequest\x1a7.scalekit.v1.auth.webauthn.FinishAuthenticationResponse\"\x83\x03\x92A\xb9\x02\x12\x1fComplete passkey authentication\x1a\x9d\x01Completes passkey authentication by validating the authenticator response. On success, returns the user ID and session token for establishing a user session.Jv\n" +
	"\x03200\x12o\n" +
	"0Authentication completed with user session token\x12;\n" +
	"9\x1a7.scalekit.v1.auth.webauthn.FinishAuthenticationResponse\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/webauthn/authentication:finish\x12\xd8\x03\n" +
	"\x0fListCredentials\x121.scalekit.v1.auth.webauthn.ListCredentialsRequest\x1a2.scalekit.v1.auth.webauthn.ListCredentialsResponse\"\xdd\x02\x92A\xaf\x02\x12\x14List user's passkeys\x1a\xb5\x01Retrieves all registered passkeys for the current user, including device information, creation timestamps, and display names. Use this to show users their registered authenticators.J_\n" +
	"\x03200\x12X\n" +
	"\x1eList of passkeys with metadata\x126\n" +
	"4\x1a2.scalekit.v1.auth.webauthn.ListCredentialsResponse\x82\xb5\x18\x02\x18T\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/webauthn/credentials\x12\xb7\x03\n" +
	"\x10DeleteCredential\x122.scalekit.v1.auth.webauthn.DeleteCredentialRequest\x1a3.scalekit.v1.auth.webauthn.DeleteCredentialResponse\"\xb9\x02\x92A\xfb\x01\x12\x10Remove a passkey\x1a\x86\x01Deletes a specific passkey credential for the current user. After removal, the authenticator can no longer be used for authentication.J^\n" +
	"\x03200\x12W\n" +
	"\x1cPasskey successfully deleted\x127\n" +
	"5\x1a3.scalekit.v1.auth.webauthn.DeleteCredentialResponse\x82\xb5\x18\x02\x18T\x82\xd3\xe4\x93\x02.*,/api/v1/webauthn/credentials/{credential_id}\x12\xc6\x03\n" +
	"\x10UpdateCredential\x122.scalekit.v1.auth.webauthn.UpdateCredentialRequest\x1a3.scalekit.v1.auth.webauthn.UpdateCredentialResponse\"\xc8\x02\x92A\x87\x02\x12\x10Rename a passkey\x1a\x84\x01Updates the display name of a passkey credential to help users identify their authenticators. Only the display name can be modified.Jl\n" +
	"\x03200\x12e\n" +
	"*Passkey successfully updated with new name\x127\n" +
	"5\x1a3.scalekit.v1.auth.webauthn.UpdateCredentialResponse\x82\xb5\x18\x02\x18\x14\x82\xd3\xe4\x93\x021:\x01*2,/api/v1/webauthn/credentials/{credential_id}\x12\xcb\x03\n" +
	"\x11GetRelatedOrigins\x123.scalekit.v1.auth.webauthn.GetRelatedOriginsRequest\x1a4.scalekit.v1.auth.webauthn.GetRelatedOriginsResponse\"\xca\x02\x92A\x94\x02\x12\x1cGet WebAuthn related origins\x1a\x8c\x01Retrieves the list of related origins configured for cross-origin passkey authentication. Serves the standard .well-known/webauthn endpoint.Je\n" +
	"\x03200\x12^\n" +
	"\"List of configured related origins\x128\n" +
	"6\x1a4.scalekit.v1.auth.webauthn.GetRelatedOriginsResponse\x82\xb5\x18\x02\x18\x01\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02\x17\x12\x15/.well-known/webauthn\x1aY\x92AV\n" +
	"\bPasskeys\x12JEndpoints for passkey-based authentication using WebAuthn/FIDO2 standards.B\xfc\x01\n" +
	"\x1dcom.scalekit.v1.auth.webauthnB\rWebauthnProtoP\x01ZDgithub.com/scalekit-inc/scalekit-sdk-go/v2/pkg/grpc/scalekit/v1/auth\xa2\x02\x04SVAW\xaa\x02\x19Scalekit.V1.Auth.Webauthn\xca\x02\x19Scalekit\\V1\\Auth\\Webauthn\xe2\x02%Scalekit\\V1\\Auth\\Webauthn\\GPBMetadata\xea\x02\x1cScalekit::V1::Auth::Webauthnb\x06proto3"

var (
	file_scalekit_v1_auth_webauthn_proto_rawDescOnce sync.Once
	file_scalekit_v1_auth_webauthn_proto_rawDescData []byte
)

func file_scalekit_v1_auth_webauthn_proto_rawDescGZIP() []byte {
	file_scalekit_v1_auth_webauthn_proto_rawDescOnce.Do(func() {
		file_scalekit_v1_auth_webauthn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scalekit_v1_auth_webauthn_proto_rawDesc), len(file_scalekit_v1_auth_webauthn_proto_rawDesc)))
	})
	return file_scalekit_v1_auth_webauthn_proto_rawDescData
}

var file_scalekit_v1_auth_webauthn_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_scalekit_v1_auth_webauthn_proto_goTypes = []any{
	(*BeginRegistrationRequest)(nil),              // 0: scalekit.v1.auth.webauthn.BeginRegistrationRequest
	(*BeginRegistrationResponse)(nil),             // 1: scalekit.v1.auth.webauthn.BeginRegistrationResponse
	(*FinishRegistrationRequest)(nil),             // 2: scalekit.v1.auth.webauthn.FinishRegistrationRequest
	(*FinishRegistrationResponse)(nil),            // 3: scalekit.v1.auth.webauthn.FinishRegistrationResponse
	(*BeginAuthenticationRequest)(nil),            // 4: scalekit.v1.auth.webauthn.BeginAuthenticationRequest
	(*BeginAuthenticationResponse)(nil),           // 5: scalekit.v1.auth.webauthn.BeginAuthenticationResponse
	(*FinishAuthenticationRequest)(nil),           // 6: scalekit.v1.auth.webauthn.FinishAuthenticationRequest
	(*AuthenticatorAssertionResponse)(nil),        // 7: scalekit.v1.auth.webauthn.AuthenticatorAssertionResponse
	(*FinishAuthenticationResponse)(nil),          // 8: scalekit.v1.auth.webauthn.FinishAuthenticationResponse
	(*WebAuthnConfiguration)(nil),                 // 9: scalekit.v1.auth.webauthn.WebAuthnConfiguration
	(*ListCredentialsRequest)(nil),                // 10: scalekit.v1.auth.webauthn.ListCredentialsRequest
	(*ListCredentialsResponse)(nil),               // 11: scalekit.v1.auth.webauthn.ListCredentialsResponse
	(*DeleteCredentialRequest)(nil),               // 12: scalekit.v1.auth.webauthn.DeleteCredentialRequest
	(*DeleteCredentialResponse)(nil),              // 13: scalekit.v1.auth.webauthn.DeleteCredentialResponse
	(*UnknownCredentialOptions)(nil),              // 14: scalekit.v1.auth.webauthn.UnknownCredentialOptions
	(*AllAcceptedCredentialsOptions)(nil),         // 15: scalekit.v1.auth.webauthn.AllAcceptedCredentialsOptions
	(*UpdateCredentialRequest)(nil),               // 16: scalekit.v1.auth.webauthn.UpdateCredentialRequest
	(*UpdateCredentialResponse)(nil),              // 17: scalekit.v1.auth.webauthn.UpdateCredentialResponse
	(*WebAuthnCredential)(nil),                    // 18: scalekit.v1.auth.webauthn.WebAuthnCredential
	(*GetRelatedOriginsRequest)(nil),              // 19: scalekit.v1.auth.webauthn.GetRelatedOriginsRequest
	(*GetRelatedOriginsResponse)(nil),             // 20: scalekit.v1.auth.webauthn.GetRelatedOriginsResponse
	(*WebAuthnCredential_AuthenticatorFlags)(nil), // 21: scalekit.v1.auth.webauthn.WebAuthnCredential.AuthenticatorFlags
	(*WebAuthnCredential_Authenticator)(nil),      // 22: scalekit.v1.auth.webauthn.WebAuthnCredential.Authenticator
	(*WebAuthnCredential_UserAgent)(nil),          // 23: scalekit.v1.auth.webauthn.WebAuthnCredential.UserAgent
	(*WebAuthnCredential_ClientInfo)(nil),         // 24: scalekit.v1.auth.webauthn.WebAuthnCredential.ClientInfo
	(*structpb.Struct)(nil),                       // 25: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),                 // 26: google.protobuf.Timestamp
}
var file_scalekit_v1_auth_webauthn_proto_depIdxs = []int32{
	25, // 0: scalekit.v1.auth.webauthn.BeginRegistrationResponse.options:type_name -> google.protobuf.Struct
	25, // 1: scalekit.v1.auth.webauthn.FinishRegistrationRequest.client_extension_results:type_name -> google.protobuf.Struct
	25, // 2: scalekit.v1.auth.webauthn.BeginAuthenticationResponse.options:type_name -> google.protobuf.Struct
	25, // 3: scalekit.v1.auth.webauthn.FinishAuthenticationRequest.client_extension_results:type_name -> google.protobuf.Struct
	7,  // 4: scalekit.v1.auth.webauthn.FinishAuthenticationRequest.response:type_name -> scalekit.v1.auth.webauthn.AuthenticatorAssertionResponse
	18, // 5: scalekit.v1.auth.webauthn.ListCredentialsResponse.credentials:type_name -> scalekit.v1.auth.webauthn.WebAuthnCredential
	15, // 6: scalekit.v1.auth.webauthn.ListCredentialsResponse.all_accepted_credentials_options:type_name -> scalekit.v1.auth.webauthn.AllAcceptedCredentialsOptions
	14, // 7: scalekit.v1.auth.webauthn.DeleteCredentialResponse.unknown_credential_options:type_name -> scalekit.v1.auth.webauthn.UnknownCredentialOptions
	18, // 8: scalekit.v1.auth.webauthn.UpdateCredentialResponse.credential:type_name -> scalekit.v1.auth.webauthn.WebAuthnCredential
	22, // 9: scalekit.v1.auth.webauthn.WebAuthnCredential.authenticator:type_name -> scalekit.v1.auth.webauthn.WebAuthnCredential.Authenticator
	21, // 10: scalekit.v1.auth.webauthn.WebAuthnCredential.authenticator_flags:type_name -> scalekit.v1.auth.webauthn.WebAuthnCredential.AuthenticatorFlags
	26, // 11: scalekit.v1.auth.webauthn.WebAuthnCredential.created_at:type_name -> google.protobuf.Timestamp
	26, // 12: scalekit.v1.auth.webauthn.WebAuthnCredential.updated_at:type_name -> google.protobuf.Timestamp
	23, // 13: scalekit.v1.auth.webauthn.WebAuthnCredential.user_agent:type_name -> scalekit.v1.auth.webauthn.WebAuthnCredential.UserAgent
	24, // 14: scalekit.v1.auth.webauthn.WebAuthnCredential.client_info:type_name -> scalekit.v1.auth.webauthn.WebAuthnCredential.ClientInfo
	0,  // 15: scalekit.v1.auth.webauthn.WebAuthnService.BeginRegistration:input_type -> scalekit.v1.auth.webauthn.BeginRegistrationRequest
	2,  // 16: scalekit.v1.auth.webauthn.WebAuthnService.FinishRegistration:input_type -> scalekit.v1.auth.webauthn.FinishRegistrationRequest
	4,  // 17: scalekit.v1.auth.webauthn.WebAuthnService.BeginAuthentication:input_type -> scalekit.v1.auth.webauthn.BeginAuthenticationRequest
	6,  // 18: scalekit.v1.auth.webauthn.WebAuthnService.FinishAuthentication:input_type -> scalekit.v1.auth.webauthn.FinishAuthenticationRequest
	10, // 19: scalekit.v1.auth.webauthn.WebAuthnService.ListCredentials:input_type -> scalekit.v1.auth.webauthn.ListCredentialsRequest
	12, // 20: scalekit.v1.auth.webauthn.WebAuthnService.DeleteCredential:input_type -> scalekit.v1.auth.webauthn.DeleteCredentialRequest
	16, // 21: scalekit.v1.auth.webauthn.WebAuthnService.UpdateCredential:input_type -> scalekit.v1.auth.webauthn.UpdateCredentialRequest
	19, // 22: scalekit.v1.auth.webauthn.WebAuthnService.GetRelatedOrigins:input_type -> scalekit.v1.auth.webauthn.GetRelatedOriginsRequest
	1,  // 23: scalekit.v1.auth.webauthn.WebAuthnService.BeginRegistration:output_type -> scalekit.v1.auth.webauthn.BeginRegistrationResponse
	3,  // 24: scalekit.v1.auth.webauthn.WebAuthnService.FinishRegistration:output_type -> scalekit.v1.auth.webauthn.FinishRegistrationResponse
	5,  // 25: scalekit.v1.auth.webauthn.WebAuthnService.BeginAuthentication:output_type -> scalekit.v1.auth.webauthn.BeginAuthenticationResponse
	8,  // 26: scalekit.v1.auth.webauthn.WebAuthnService.FinishAuthentication:output_type -> scalekit.v1.auth.webauthn.FinishAuthenticationResponse
	11, // 27: scalekit.v1.auth.webauthn.WebAuthnService.ListCredentials:output_type -> scalekit.v1.auth.webauthn.ListCredentialsResponse
	13, // 28: scalekit.v1.auth.webauthn.WebAuthnService.DeleteCredential:output_type -> scalekit.v1.auth.webauthn.DeleteCredentialResponse
	17, // 29: scalekit.v1.auth.webauthn.WebAuthnService.UpdateCredential:output_type -> scalekit.v1.auth.webauthn.UpdateCredentialResponse
	20, // 30: scalekit.v1.auth.webauthn.WebAuthnService.GetRelatedOrigins:output_type -> scalekit.v1.auth.webauthn.GetRelatedOriginsResponse
	23, // [23:31] is the sub-list for method output_type
	15, // [15:23] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_scalekit_v1_auth_webauthn_proto_init() }
func file_scalekit_v1_auth_webauthn_proto_init() {
	if File_scalekit_v1_auth_webauthn_proto != nil {
		return
	}
	file_scalekit_v1_auth_webauthn_proto_msgTypes[4].OneofWrappers = []any{}
	file_scalekit_v1_auth_webauthn_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scalekit_v1_auth_webauthn_proto_rawDesc), len(file_scalekit_v1_auth_webauthn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scalekit_v1_auth_webauthn_proto_goTypes,
		DependencyIndexes: file_scalekit_v1_auth_webauthn_proto_depIdxs,
		MessageInfos:      file_scalekit_v1_auth_webauthn_proto_msgTypes,
	}.Build()
	File_scalekit_v1_auth_webauthn_proto = out.File
	file_scalekit_v1_auth_webauthn_proto_goTypes = nil
	file_scalekit_v1_auth_webauthn_proto_depIdxs = nil
}
