// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: scalekit/v1/users/users.proto

package usersconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	users "github.com/scalekit-inc/scalekit-sdk-go/pkg/grpc/scalekit/v1/users"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "scalekit.v1.users.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceCreateUserProcedure is the fully-qualified name of the UserService's CreateUser RPC.
	UserServiceCreateUserProcedure = "/scalekit.v1.users.UserService/CreateUser"
	// UserServiceUpdateUserProcedure is the fully-qualified name of the UserService's UpdateUser RPC.
	UserServiceUpdateUserProcedure = "/scalekit.v1.users.UserService/UpdateUser"
	// UserServiceGetUserProcedure is the fully-qualified name of the UserService's GetUser RPC.
	UserServiceGetUserProcedure = "/scalekit.v1.users.UserService/GetUser"
	// UserServiceListUsersProcedure is the fully-qualified name of the UserService's ListUsers RPC.
	UserServiceListUsersProcedure = "/scalekit.v1.users.UserService/ListUsers"
	// UserServiceDeleteUserProcedure is the fully-qualified name of the UserService's DeleteUser RPC.
	UserServiceDeleteUserProcedure = "/scalekit.v1.users.UserService/DeleteUser"
	// UserServiceAddUserToOrganizationProcedure is the fully-qualified name of the UserService's
	// AddUserToOrganization RPC.
	UserServiceAddUserToOrganizationProcedure = "/scalekit.v1.users.UserService/AddUserToOrganization"
)

// UserServiceClient is a client for the scalekit.v1.users.UserService service.
type UserServiceClient interface {
	CreateUser(context.Context, *connect.Request[users.CreateUserRequest]) (*connect.Response[users.CreateUserResponse], error)
	UpdateUser(context.Context, *connect.Request[users.UpdateUserRequest]) (*connect.Response[users.UpdateUserResponse], error)
	GetUser(context.Context, *connect.Request[users.GetUserRequest]) (*connect.Response[users.GetUserResponse], error)
	ListUsers(context.Context, *connect.Request[users.ListUserRequest]) (*connect.Response[users.ListUserResponse], error)
	DeleteUser(context.Context, *connect.Request[users.DeleteUserRequest]) (*connect.Response[emptypb.Empty], error)
	AddUserToOrganization(context.Context, *connect.Request[users.AddUserRequest]) (*connect.Response[users.AddUserResponse], error)
}

// NewUserServiceClient constructs a client for the scalekit.v1.users.UserService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := users.File_scalekit_v1_users_users_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		createUser: connect.NewClient[users.CreateUserRequest, users.CreateUserResponse](
			httpClient,
			baseURL+UserServiceCreateUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[users.UpdateUserRequest, users.UpdateUserResponse](
			httpClient,
			baseURL+UserServiceUpdateUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[users.GetUserRequest, users.GetUserResponse](
			httpClient,
			baseURL+UserServiceGetUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		listUsers: connect.NewClient[users.ListUserRequest, users.ListUserResponse](
			httpClient,
			baseURL+UserServiceListUsersProcedure,
			connect.WithSchema(userServiceMethods.ByName("ListUsers")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[users.DeleteUserRequest, emptypb.Empty](
			httpClient,
			baseURL+UserServiceDeleteUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
		addUserToOrganization: connect.NewClient[users.AddUserRequest, users.AddUserResponse](
			httpClient,
			baseURL+UserServiceAddUserToOrganizationProcedure,
			connect.WithSchema(userServiceMethods.ByName("AddUserToOrganization")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	createUser            *connect.Client[users.CreateUserRequest, users.CreateUserResponse]
	updateUser            *connect.Client[users.UpdateUserRequest, users.UpdateUserResponse]
	getUser               *connect.Client[users.GetUserRequest, users.GetUserResponse]
	listUsers             *connect.Client[users.ListUserRequest, users.ListUserResponse]
	deleteUser            *connect.Client[users.DeleteUserRequest, emptypb.Empty]
	addUserToOrganization *connect.Client[users.AddUserRequest, users.AddUserResponse]
}

// CreateUser calls scalekit.v1.users.UserService.CreateUser.
func (c *userServiceClient) CreateUser(ctx context.Context, req *connect.Request[users.CreateUserRequest]) (*connect.Response[users.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// UpdateUser calls scalekit.v1.users.UserService.UpdateUser.
func (c *userServiceClient) UpdateUser(ctx context.Context, req *connect.Request[users.UpdateUserRequest]) (*connect.Response[users.UpdateUserResponse], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// GetUser calls scalekit.v1.users.UserService.GetUser.
func (c *userServiceClient) GetUser(ctx context.Context, req *connect.Request[users.GetUserRequest]) (*connect.Response[users.GetUserResponse], error) {
	return c.getUser.CallUnary(ctx, req)
}

// ListUsers calls scalekit.v1.users.UserService.ListUsers.
func (c *userServiceClient) ListUsers(ctx context.Context, req *connect.Request[users.ListUserRequest]) (*connect.Response[users.ListUserResponse], error) {
	return c.listUsers.CallUnary(ctx, req)
}

// DeleteUser calls scalekit.v1.users.UserService.DeleteUser.
func (c *userServiceClient) DeleteUser(ctx context.Context, req *connect.Request[users.DeleteUserRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// AddUserToOrganization calls scalekit.v1.users.UserService.AddUserToOrganization.
func (c *userServiceClient) AddUserToOrganization(ctx context.Context, req *connect.Request[users.AddUserRequest]) (*connect.Response[users.AddUserResponse], error) {
	return c.addUserToOrganization.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the scalekit.v1.users.UserService service.
type UserServiceHandler interface {
	CreateUser(context.Context, *connect.Request[users.CreateUserRequest]) (*connect.Response[users.CreateUserResponse], error)
	UpdateUser(context.Context, *connect.Request[users.UpdateUserRequest]) (*connect.Response[users.UpdateUserResponse], error)
	GetUser(context.Context, *connect.Request[users.GetUserRequest]) (*connect.Response[users.GetUserResponse], error)
	ListUsers(context.Context, *connect.Request[users.ListUserRequest]) (*connect.Response[users.ListUserResponse], error)
	DeleteUser(context.Context, *connect.Request[users.DeleteUserRequest]) (*connect.Response[emptypb.Empty], error)
	AddUserToOrganization(context.Context, *connect.Request[users.AddUserRequest]) (*connect.Response[users.AddUserResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := users.File_scalekit_v1_users_users_proto.Services().ByName("UserService").Methods()
	userServiceCreateUserHandler := connect.NewUnaryHandler(
		UserServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(userServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceUpdateUserHandler := connect.NewUnaryHandler(
		UserServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(userServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetUserHandler := connect.NewUnaryHandler(
		UserServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(userServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceListUsersHandler := connect.NewUnaryHandler(
		UserServiceListUsersProcedure,
		svc.ListUsers,
		connect.WithSchema(userServiceMethods.ByName("ListUsers")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceDeleteUserHandler := connect.NewUnaryHandler(
		UserServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(userServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceAddUserToOrganizationHandler := connect.NewUnaryHandler(
		UserServiceAddUserToOrganizationProcedure,
		svc.AddUserToOrganization,
		connect.WithSchema(userServiceMethods.ByName("AddUserToOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	return "/scalekit.v1.users.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceCreateUserProcedure:
			userServiceCreateUserHandler.ServeHTTP(w, r)
		case UserServiceUpdateUserProcedure:
			userServiceUpdateUserHandler.ServeHTTP(w, r)
		case UserServiceGetUserProcedure:
			userServiceGetUserHandler.ServeHTTP(w, r)
		case UserServiceListUsersProcedure:
			userServiceListUsersHandler.ServeHTTP(w, r)
		case UserServiceDeleteUserProcedure:
			userServiceDeleteUserHandler.ServeHTTP(w, r)
		case UserServiceAddUserToOrganizationProcedure:
			userServiceAddUserToOrganizationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) CreateUser(context.Context, *connect.Request[users.CreateUserRequest]) (*connect.Response[users.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.users.UserService.CreateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) UpdateUser(context.Context, *connect.Request[users.UpdateUserRequest]) (*connect.Response[users.UpdateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.users.UserService.UpdateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) GetUser(context.Context, *connect.Request[users.GetUserRequest]) (*connect.Response[users.GetUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.users.UserService.GetUser is not implemented"))
}

func (UnimplementedUserServiceHandler) ListUsers(context.Context, *connect.Request[users.ListUserRequest]) (*connect.Response[users.ListUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.users.UserService.ListUsers is not implemented"))
}

func (UnimplementedUserServiceHandler) DeleteUser(context.Context, *connect.Request[users.DeleteUserRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.users.UserService.DeleteUser is not implemented"))
}

func (UnimplementedUserServiceHandler) AddUserToOrganization(context.Context, *connect.Request[users.AddUserRequest]) (*connect.Response[users.AddUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.users.UserService.AddUserToOrganization is not implemented"))
}
