// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: scalekit/v1/errdetails/errdetails.proto

package errdetailsconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	errdetails "github.com/scalekit-inc/scalekit-sdk-go/v2/pkg/grpc/scalekit/v1/errdetails"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DummyName is the fully-qualified name of the Dummy service.
	DummyName = "scalekit.v1.errdetails.Dummy"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DummyDummyServiceProcedure is the fully-qualified name of the Dummy's DummyService RPC.
	DummyDummyServiceProcedure = "/scalekit.v1.errdetails.Dummy/DummyService"
)

// DummyClient is a client for the scalekit.v1.errdetails.Dummy service.
type DummyClient interface {
	DummyService(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[errdetails.ErrorInfo], error)
}

// NewDummyClient constructs a client for the scalekit.v1.errdetails.Dummy service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDummyClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DummyClient {
	baseURL = strings.TrimRight(baseURL, "/")
	dummyMethods := errdetails.File_scalekit_v1_errdetails_errdetails_proto.Services().ByName("Dummy").Methods()
	return &dummyClient{
		dummyService: connect.NewClient[emptypb.Empty, errdetails.ErrorInfo](
			httpClient,
			baseURL+DummyDummyServiceProcedure,
			connect.WithSchema(dummyMethods.ByName("DummyService")),
			connect.WithClientOptions(opts...),
		),
	}
}

// dummyClient implements DummyClient.
type dummyClient struct {
	dummyService *connect.Client[emptypb.Empty, errdetails.ErrorInfo]
}

// DummyService calls scalekit.v1.errdetails.Dummy.DummyService.
func (c *dummyClient) DummyService(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[errdetails.ErrorInfo], error) {
	return c.dummyService.CallUnary(ctx, req)
}

// DummyHandler is an implementation of the scalekit.v1.errdetails.Dummy service.
type DummyHandler interface {
	DummyService(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[errdetails.ErrorInfo], error)
}

// NewDummyHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDummyHandler(svc DummyHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dummyMethods := errdetails.File_scalekit_v1_errdetails_errdetails_proto.Services().ByName("Dummy").Methods()
	dummyDummyServiceHandler := connect.NewUnaryHandler(
		DummyDummyServiceProcedure,
		svc.DummyService,
		connect.WithSchema(dummyMethods.ByName("DummyService")),
		connect.WithHandlerOptions(opts...),
	)
	return "/scalekit.v1.errdetails.Dummy/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DummyDummyServiceProcedure:
			dummyDummyServiceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDummyHandler returns CodeUnimplemented from all methods.
type UnimplementedDummyHandler struct{}

func (UnimplementedDummyHandler) DummyService(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[errdetails.ErrorInfo], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.errdetails.Dummy.DummyService is not implemented"))
}
