// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: scalekit/v1/auth/auth.proto

package authconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	auth "github.com/scalekit-inc/scalekit-sdk-go/v2/pkg/grpc/scalekit/v1/auth"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "scalekit.v1.auth.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceListAuthMethodsProcedure is the fully-qualified name of the AuthService's
	// ListAuthMethods RPC.
	AuthServiceListAuthMethodsProcedure = "/scalekit.v1.auth.AuthService/ListAuthMethods"
	// AuthServiceDiscoveryAuthMethodProcedure is the fully-qualified name of the AuthService's
	// DiscoveryAuthMethod RPC.
	AuthServiceDiscoveryAuthMethodProcedure = "/scalekit.v1.auth.AuthService/DiscoveryAuthMethod"
	// AuthServiceVerifyPasswordLessOtpProcedure is the fully-qualified name of the AuthService's
	// VerifyPasswordLessOtp RPC.
	AuthServiceVerifyPasswordLessOtpProcedure = "/scalekit.v1.auth.AuthService/VerifyPasswordLessOtp"
	// AuthServiceResendPasswordlessProcedure is the fully-qualified name of the AuthService's
	// ResendPasswordless RPC.
	AuthServiceResendPasswordlessProcedure = "/scalekit.v1.auth.AuthService/ResendPasswordless"
	// AuthServiceListUserOrganizationsProcedure is the fully-qualified name of the AuthService's
	// ListUserOrganizations RPC.
	AuthServiceListUserOrganizationsProcedure = "/scalekit.v1.auth.AuthService/ListUserOrganizations"
	// AuthServiceSignupOrganizationProcedure is the fully-qualified name of the AuthService's
	// SignupOrganization RPC.
	AuthServiceSignupOrganizationProcedure = "/scalekit.v1.auth.AuthService/SignupOrganization"
	// AuthServiceGetAuthStateProcedure is the fully-qualified name of the AuthService's GetAuthState
	// RPC.
	AuthServiceGetAuthStateProcedure = "/scalekit.v1.auth.AuthService/GetAuthState"
	// AuthServiceGetAuthErrorProcedure is the fully-qualified name of the AuthService's GetAuthError
	// RPC.
	AuthServiceGetAuthErrorProcedure = "/scalekit.v1.auth.AuthService/GetAuthError"
	// AuthServiceLogoutProcedure is the fully-qualified name of the AuthService's Logout RPC.
	AuthServiceLogoutProcedure = "/scalekit.v1.auth.AuthService/Logout"
	// AuthServiceGetAuthCustomizationsProcedure is the fully-qualified name of the AuthService's
	// GetAuthCustomizations RPC.
	AuthServiceGetAuthCustomizationsProcedure = "/scalekit.v1.auth.AuthService/GetAuthCustomizations"
	// AuthServiceGetAuthFeaturesProcedure is the fully-qualified name of the AuthService's
	// GetAuthFeatures RPC.
	AuthServiceGetAuthFeaturesProcedure = "/scalekit.v1.auth.AuthService/GetAuthFeatures"
	// AuthServiceUpdateLoginUserDetailsProcedure is the fully-qualified name of the AuthService's
	// UpdateLoginUserDetails RPC.
	AuthServiceUpdateLoginUserDetailsProcedure = "/scalekit.v1.auth.AuthService/UpdateLoginUserDetails"
)

// AuthServiceClient is a client for the scalekit.v1.auth.AuthService service.
type AuthServiceClient interface {
	ListAuthMethods(context.Context, *connect.Request[auth.ListAuthMethodsRequest]) (*connect.Response[auth.ListAuthMethodsResponse], error)
	DiscoveryAuthMethod(context.Context, *connect.Request[auth.DiscoveryAuthMethodRequest]) (*connect.Response[auth.DiscoveryAuthMethodResponse], error)
	VerifyPasswordLessOtp(context.Context, *connect.Request[auth.VerifyPasswordLessOtpRequest]) (*connect.Response[auth.VerifyPasswordLessOtpResponse], error)
	ResendPasswordless(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	ListUserOrganizations(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[auth.ListUserOrganizationsResponse], error)
	SignupOrganization(context.Context, *connect.Request[auth.SignupOrganizationRequest]) (*connect.Response[auth.SignupOrganizationResponse], error)
	GetAuthState(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[auth.GetAuthStateResponse], error)
	GetAuthError(context.Context, *connect.Request[auth.GetAuthErrorRequest]) (*connect.Response[auth.GetAuthErrorResponse], error)
	Logout(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	GetAuthCustomizations(context.Context, *connect.Request[auth.GetAuthCustomizationsRequest]) (*connect.Response[auth.GetAuthCustomizationsResponse], error)
	GetAuthFeatures(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[auth.GetAuthFeaturesResponse], error)
	UpdateLoginUserDetails(context.Context, *connect.Request[auth.UpdateLoginUserDetailsRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewAuthServiceClient constructs a client for the scalekit.v1.auth.AuthService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := auth.File_scalekit_v1_auth_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		listAuthMethods: connect.NewClient[auth.ListAuthMethodsRequest, auth.ListAuthMethodsResponse](
			httpClient,
			baseURL+AuthServiceListAuthMethodsProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListAuthMethods")),
			connect.WithClientOptions(opts...),
		),
		discoveryAuthMethod: connect.NewClient[auth.DiscoveryAuthMethodRequest, auth.DiscoveryAuthMethodResponse](
			httpClient,
			baseURL+AuthServiceDiscoveryAuthMethodProcedure,
			connect.WithSchema(authServiceMethods.ByName("DiscoveryAuthMethod")),
			connect.WithClientOptions(opts...),
		),
		verifyPasswordLessOtp: connect.NewClient[auth.VerifyPasswordLessOtpRequest, auth.VerifyPasswordLessOtpResponse](
			httpClient,
			baseURL+AuthServiceVerifyPasswordLessOtpProcedure,
			connect.WithSchema(authServiceMethods.ByName("VerifyPasswordLessOtp")),
			connect.WithClientOptions(opts...),
		),
		resendPasswordless: connect.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceResendPasswordlessProcedure,
			connect.WithSchema(authServiceMethods.ByName("ResendPasswordless")),
			connect.WithClientOptions(opts...),
		),
		listUserOrganizations: connect.NewClient[emptypb.Empty, auth.ListUserOrganizationsResponse](
			httpClient,
			baseURL+AuthServiceListUserOrganizationsProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListUserOrganizations")),
			connect.WithClientOptions(opts...),
		),
		signupOrganization: connect.NewClient[auth.SignupOrganizationRequest, auth.SignupOrganizationResponse](
			httpClient,
			baseURL+AuthServiceSignupOrganizationProcedure,
			connect.WithSchema(authServiceMethods.ByName("SignupOrganization")),
			connect.WithClientOptions(opts...),
		),
		getAuthState: connect.NewClient[emptypb.Empty, auth.GetAuthStateResponse](
			httpClient,
			baseURL+AuthServiceGetAuthStateProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetAuthState")),
			connect.WithClientOptions(opts...),
		),
		getAuthError: connect.NewClient[auth.GetAuthErrorRequest, auth.GetAuthErrorResponse](
			httpClient,
			baseURL+AuthServiceGetAuthErrorProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetAuthError")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceLogoutProcedure,
			connect.WithSchema(authServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
		getAuthCustomizations: connect.NewClient[auth.GetAuthCustomizationsRequest, auth.GetAuthCustomizationsResponse](
			httpClient,
			baseURL+AuthServiceGetAuthCustomizationsProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetAuthCustomizations")),
			connect.WithClientOptions(opts...),
		),
		getAuthFeatures: connect.NewClient[emptypb.Empty, auth.GetAuthFeaturesResponse](
			httpClient,
			baseURL+AuthServiceGetAuthFeaturesProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetAuthFeatures")),
			connect.WithClientOptions(opts...),
		),
		updateLoginUserDetails: connect.NewClient[auth.UpdateLoginUserDetailsRequest, emptypb.Empty](
			httpClient,
			baseURL+AuthServiceUpdateLoginUserDetailsProcedure,
			connect.WithSchema(authServiceMethods.ByName("UpdateLoginUserDetails")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	listAuthMethods        *connect.Client[auth.ListAuthMethodsRequest, auth.ListAuthMethodsResponse]
	discoveryAuthMethod    *connect.Client[auth.DiscoveryAuthMethodRequest, auth.DiscoveryAuthMethodResponse]
	verifyPasswordLessOtp  *connect.Client[auth.VerifyPasswordLessOtpRequest, auth.VerifyPasswordLessOtpResponse]
	resendPasswordless     *connect.Client[emptypb.Empty, emptypb.Empty]
	listUserOrganizations  *connect.Client[emptypb.Empty, auth.ListUserOrganizationsResponse]
	signupOrganization     *connect.Client[auth.SignupOrganizationRequest, auth.SignupOrganizationResponse]
	getAuthState           *connect.Client[emptypb.Empty, auth.GetAuthStateResponse]
	getAuthError           *connect.Client[auth.GetAuthErrorRequest, auth.GetAuthErrorResponse]
	logout                 *connect.Client[emptypb.Empty, emptypb.Empty]
	getAuthCustomizations  *connect.Client[auth.GetAuthCustomizationsRequest, auth.GetAuthCustomizationsResponse]
	getAuthFeatures        *connect.Client[emptypb.Empty, auth.GetAuthFeaturesResponse]
	updateLoginUserDetails *connect.Client[auth.UpdateLoginUserDetailsRequest, emptypb.Empty]
}

// ListAuthMethods calls scalekit.v1.auth.AuthService.ListAuthMethods.
func (c *authServiceClient) ListAuthMethods(ctx context.Context, req *connect.Request[auth.ListAuthMethodsRequest]) (*connect.Response[auth.ListAuthMethodsResponse], error) {
	return c.listAuthMethods.CallUnary(ctx, req)
}

// DiscoveryAuthMethod calls scalekit.v1.auth.AuthService.DiscoveryAuthMethod.
func (c *authServiceClient) DiscoveryAuthMethod(ctx context.Context, req *connect.Request[auth.DiscoveryAuthMethodRequest]) (*connect.Response[auth.DiscoveryAuthMethodResponse], error) {
	return c.discoveryAuthMethod.CallUnary(ctx, req)
}

// VerifyPasswordLessOtp calls scalekit.v1.auth.AuthService.VerifyPasswordLessOtp.
func (c *authServiceClient) VerifyPasswordLessOtp(ctx context.Context, req *connect.Request[auth.VerifyPasswordLessOtpRequest]) (*connect.Response[auth.VerifyPasswordLessOtpResponse], error) {
	return c.verifyPasswordLessOtp.CallUnary(ctx, req)
}

// ResendPasswordless calls scalekit.v1.auth.AuthService.ResendPasswordless.
func (c *authServiceClient) ResendPasswordless(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return c.resendPasswordless.CallUnary(ctx, req)
}

// ListUserOrganizations calls scalekit.v1.auth.AuthService.ListUserOrganizations.
func (c *authServiceClient) ListUserOrganizations(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[auth.ListUserOrganizationsResponse], error) {
	return c.listUserOrganizations.CallUnary(ctx, req)
}

// SignupOrganization calls scalekit.v1.auth.AuthService.SignupOrganization.
func (c *authServiceClient) SignupOrganization(ctx context.Context, req *connect.Request[auth.SignupOrganizationRequest]) (*connect.Response[auth.SignupOrganizationResponse], error) {
	return c.signupOrganization.CallUnary(ctx, req)
}

// GetAuthState calls scalekit.v1.auth.AuthService.GetAuthState.
func (c *authServiceClient) GetAuthState(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[auth.GetAuthStateResponse], error) {
	return c.getAuthState.CallUnary(ctx, req)
}

// GetAuthError calls scalekit.v1.auth.AuthService.GetAuthError.
func (c *authServiceClient) GetAuthError(ctx context.Context, req *connect.Request[auth.GetAuthErrorRequest]) (*connect.Response[auth.GetAuthErrorResponse], error) {
	return c.getAuthError.CallUnary(ctx, req)
}

// Logout calls scalekit.v1.auth.AuthService.Logout.
func (c *authServiceClient) Logout(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return c.logout.CallUnary(ctx, req)
}

// GetAuthCustomizations calls scalekit.v1.auth.AuthService.GetAuthCustomizations.
func (c *authServiceClient) GetAuthCustomizations(ctx context.Context, req *connect.Request[auth.GetAuthCustomizationsRequest]) (*connect.Response[auth.GetAuthCustomizationsResponse], error) {
	return c.getAuthCustomizations.CallUnary(ctx, req)
}

// GetAuthFeatures calls scalekit.v1.auth.AuthService.GetAuthFeatures.
func (c *authServiceClient) GetAuthFeatures(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[auth.GetAuthFeaturesResponse], error) {
	return c.getAuthFeatures.CallUnary(ctx, req)
}

// UpdateLoginUserDetails calls scalekit.v1.auth.AuthService.UpdateLoginUserDetails.
func (c *authServiceClient) UpdateLoginUserDetails(ctx context.Context, req *connect.Request[auth.UpdateLoginUserDetailsRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.updateLoginUserDetails.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the scalekit.v1.auth.AuthService service.
type AuthServiceHandler interface {
	ListAuthMethods(context.Context, *connect.Request[auth.ListAuthMethodsRequest]) (*connect.Response[auth.ListAuthMethodsResponse], error)
	DiscoveryAuthMethod(context.Context, *connect.Request[auth.DiscoveryAuthMethodRequest]) (*connect.Response[auth.DiscoveryAuthMethodResponse], error)
	VerifyPasswordLessOtp(context.Context, *connect.Request[auth.VerifyPasswordLessOtpRequest]) (*connect.Response[auth.VerifyPasswordLessOtpResponse], error)
	ResendPasswordless(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	ListUserOrganizations(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[auth.ListUserOrganizationsResponse], error)
	SignupOrganization(context.Context, *connect.Request[auth.SignupOrganizationRequest]) (*connect.Response[auth.SignupOrganizationResponse], error)
	GetAuthState(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[auth.GetAuthStateResponse], error)
	GetAuthError(context.Context, *connect.Request[auth.GetAuthErrorRequest]) (*connect.Response[auth.GetAuthErrorResponse], error)
	Logout(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	GetAuthCustomizations(context.Context, *connect.Request[auth.GetAuthCustomizationsRequest]) (*connect.Response[auth.GetAuthCustomizationsResponse], error)
	GetAuthFeatures(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[auth.GetAuthFeaturesResponse], error)
	UpdateLoginUserDetails(context.Context, *connect.Request[auth.UpdateLoginUserDetailsRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := auth.File_scalekit_v1_auth_auth_proto.Services().ByName("AuthService").Methods()
	authServiceListAuthMethodsHandler := connect.NewUnaryHandler(
		AuthServiceListAuthMethodsProcedure,
		svc.ListAuthMethods,
		connect.WithSchema(authServiceMethods.ByName("ListAuthMethods")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceDiscoveryAuthMethodHandler := connect.NewUnaryHandler(
		AuthServiceDiscoveryAuthMethodProcedure,
		svc.DiscoveryAuthMethod,
		connect.WithSchema(authServiceMethods.ByName("DiscoveryAuthMethod")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceVerifyPasswordLessOtpHandler := connect.NewUnaryHandler(
		AuthServiceVerifyPasswordLessOtpProcedure,
		svc.VerifyPasswordLessOtp,
		connect.WithSchema(authServiceMethods.ByName("VerifyPasswordLessOtp")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceResendPasswordlessHandler := connect.NewUnaryHandler(
		AuthServiceResendPasswordlessProcedure,
		svc.ResendPasswordless,
		connect.WithSchema(authServiceMethods.ByName("ResendPasswordless")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListUserOrganizationsHandler := connect.NewUnaryHandler(
		AuthServiceListUserOrganizationsProcedure,
		svc.ListUserOrganizations,
		connect.WithSchema(authServiceMethods.ByName("ListUserOrganizations")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceSignupOrganizationHandler := connect.NewUnaryHandler(
		AuthServiceSignupOrganizationProcedure,
		svc.SignupOrganization,
		connect.WithSchema(authServiceMethods.ByName("SignupOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetAuthStateHandler := connect.NewUnaryHandler(
		AuthServiceGetAuthStateProcedure,
		svc.GetAuthState,
		connect.WithSchema(authServiceMethods.ByName("GetAuthState")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetAuthErrorHandler := connect.NewUnaryHandler(
		AuthServiceGetAuthErrorProcedure,
		svc.GetAuthError,
		connect.WithSchema(authServiceMethods.ByName("GetAuthError")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLogoutHandler := connect.NewUnaryHandler(
		AuthServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(authServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetAuthCustomizationsHandler := connect.NewUnaryHandler(
		AuthServiceGetAuthCustomizationsProcedure,
		svc.GetAuthCustomizations,
		connect.WithSchema(authServiceMethods.ByName("GetAuthCustomizations")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetAuthFeaturesHandler := connect.NewUnaryHandler(
		AuthServiceGetAuthFeaturesProcedure,
		svc.GetAuthFeatures,
		connect.WithSchema(authServiceMethods.ByName("GetAuthFeatures")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceUpdateLoginUserDetailsHandler := connect.NewUnaryHandler(
		AuthServiceUpdateLoginUserDetailsProcedure,
		svc.UpdateLoginUserDetails,
		connect.WithSchema(authServiceMethods.ByName("UpdateLoginUserDetails")),
		connect.WithHandlerOptions(opts...),
	)
	return "/scalekit.v1.auth.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceListAuthMethodsProcedure:
			authServiceListAuthMethodsHandler.ServeHTTP(w, r)
		case AuthServiceDiscoveryAuthMethodProcedure:
			authServiceDiscoveryAuthMethodHandler.ServeHTTP(w, r)
		case AuthServiceVerifyPasswordLessOtpProcedure:
			authServiceVerifyPasswordLessOtpHandler.ServeHTTP(w, r)
		case AuthServiceResendPasswordlessProcedure:
			authServiceResendPasswordlessHandler.ServeHTTP(w, r)
		case AuthServiceListUserOrganizationsProcedure:
			authServiceListUserOrganizationsHandler.ServeHTTP(w, r)
		case AuthServiceSignupOrganizationProcedure:
			authServiceSignupOrganizationHandler.ServeHTTP(w, r)
		case AuthServiceGetAuthStateProcedure:
			authServiceGetAuthStateHandler.ServeHTTP(w, r)
		case AuthServiceGetAuthErrorProcedure:
			authServiceGetAuthErrorHandler.ServeHTTP(w, r)
		case AuthServiceLogoutProcedure:
			authServiceLogoutHandler.ServeHTTP(w, r)
		case AuthServiceGetAuthCustomizationsProcedure:
			authServiceGetAuthCustomizationsHandler.ServeHTTP(w, r)
		case AuthServiceGetAuthFeaturesProcedure:
			authServiceGetAuthFeaturesHandler.ServeHTTP(w, r)
		case AuthServiceUpdateLoginUserDetailsProcedure:
			authServiceUpdateLoginUserDetailsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) ListAuthMethods(context.Context, *connect.Request[auth.ListAuthMethodsRequest]) (*connect.Response[auth.ListAuthMethodsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.auth.AuthService.ListAuthMethods is not implemented"))
}

func (UnimplementedAuthServiceHandler) DiscoveryAuthMethod(context.Context, *connect.Request[auth.DiscoveryAuthMethodRequest]) (*connect.Response[auth.DiscoveryAuthMethodResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.auth.AuthService.DiscoveryAuthMethod is not implemented"))
}

func (UnimplementedAuthServiceHandler) VerifyPasswordLessOtp(context.Context, *connect.Request[auth.VerifyPasswordLessOtpRequest]) (*connect.Response[auth.VerifyPasswordLessOtpResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.auth.AuthService.VerifyPasswordLessOtp is not implemented"))
}

func (UnimplementedAuthServiceHandler) ResendPasswordless(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.auth.AuthService.ResendPasswordless is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListUserOrganizations(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[auth.ListUserOrganizationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.auth.AuthService.ListUserOrganizations is not implemented"))
}

func (UnimplementedAuthServiceHandler) SignupOrganization(context.Context, *connect.Request[auth.SignupOrganizationRequest]) (*connect.Response[auth.SignupOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.auth.AuthService.SignupOrganization is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetAuthState(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[auth.GetAuthStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.auth.AuthService.GetAuthState is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetAuthError(context.Context, *connect.Request[auth.GetAuthErrorRequest]) (*connect.Response[auth.GetAuthErrorResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.auth.AuthService.GetAuthError is not implemented"))
}

func (UnimplementedAuthServiceHandler) Logout(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.auth.AuthService.Logout is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetAuthCustomizations(context.Context, *connect.Request[auth.GetAuthCustomizationsRequest]) (*connect.Response[auth.GetAuthCustomizationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.auth.AuthService.GetAuthCustomizations is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetAuthFeatures(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[auth.GetAuthFeaturesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.auth.AuthService.GetAuthFeatures is not implemented"))
}

func (UnimplementedAuthServiceHandler) UpdateLoginUserDetails(context.Context, *connect.Request[auth.UpdateLoginUserDetailsRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.auth.AuthService.UpdateLoginUserDetails is not implemented"))
}
