// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: scalekit/v1/auditlogs/auditlogs.proto

package auditlogs

import (
	_ "github.com/scalekit-inc/scalekit-sdk-go/v2/pkg/grpc/scalekit/v1/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAuthLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      uint32                 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Status        []string               `protobuf:"bytes,4,rep,name=status,proto3" json:"status,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ResourceId    string                 `protobuf:"bytes,7,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthLogRequest) Reset() {
	*x = ListAuthLogRequest{}
	mi := &file_scalekit_v1_auditlogs_auditlogs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthLogRequest) ProtoMessage() {}

func (x *ListAuthLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auditlogs_auditlogs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthLogRequest.ProtoReflect.Descriptor instead.
func (*ListAuthLogRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auditlogs_auditlogs_proto_rawDescGZIP(), []int{0}
}

func (x *ListAuthLogRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAuthLogRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAuthLogRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ListAuthLogRequest) GetStatus() []string {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListAuthLogRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListAuthLogRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListAuthLogRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ListAuthLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextPageToken string                 `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	PrevPageToken string                 `protobuf:"bytes,2,opt,name=prev_page_token,json=prevPageToken,proto3" json:"prev_page_token,omitempty"`
	TotalSize     uint32                 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	AuthRequests  []*AuthLogRequest      `protobuf:"bytes,4,rep,name=authRequests,proto3" json:"authRequests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthLogResponse) Reset() {
	*x = ListAuthLogResponse{}
	mi := &file_scalekit_v1_auditlogs_auditlogs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthLogResponse) ProtoMessage() {}

func (x *ListAuthLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auditlogs_auditlogs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthLogResponse.ProtoReflect.Descriptor instead.
func (*ListAuthLogResponse) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auditlogs_auditlogs_proto_rawDescGZIP(), []int{1}
}

func (x *ListAuthLogResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAuthLogResponse) GetPrevPageToken() string {
	if x != nil {
		return x.PrevPageToken
	}
	return ""
}

func (x *ListAuthLogResponse) GetTotalSize() uint32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListAuthLogResponse) GetAuthRequests() []*AuthLogRequest {
	if x != nil {
		return x.AuthRequests
	}
	return nil
}

type AuthLogRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId     string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	EnvironmentId      string                 `protobuf:"bytes,2,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	ConnectionId       string                 `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	AuthRequestId      string                 `protobuf:"bytes,4,opt,name=auth_request_id,json=authRequestId,proto3" json:"auth_request_id,omitempty"`
	Email              string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	ConnectionType     string                 `protobuf:"bytes,6,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"`
	ConnectionProvider string                 `protobuf:"bytes,7,opt,name=connection_provider,json=connectionProvider,proto3" json:"connection_provider,omitempty"`
	Status             string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ConnectionDetails  []*ConnectionDetails   `protobuf:"bytes,10,rep,name=connection_details,json=connectionDetails,proto3" json:"connection_details,omitempty"`
	Workflow           string                 `protobuf:"bytes,11,opt,name=workflow,proto3" json:"workflow,omitempty"`
	ResourceId         string                 `protobuf:"bytes,12,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName       string                 `protobuf:"bytes,13,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ResourceType       string                 `protobuf:"bytes,14,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuthLogRequest) Reset() {
	*x = AuthLogRequest{}
	mi := &file_scalekit_v1_auditlogs_auditlogs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLogRequest) ProtoMessage() {}

func (x *AuthLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auditlogs_auditlogs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLogRequest.ProtoReflect.Descriptor instead.
func (*AuthLogRequest) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auditlogs_auditlogs_proto_rawDescGZIP(), []int{2}
}

func (x *AuthLogRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AuthLogRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *AuthLogRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *AuthLogRequest) GetAuthRequestId() string {
	if x != nil {
		return x.AuthRequestId
	}
	return ""
}

func (x *AuthLogRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthLogRequest) GetConnectionType() string {
	if x != nil {
		return x.ConnectionType
	}
	return ""
}

func (x *AuthLogRequest) GetConnectionProvider() string {
	if x != nil {
		return x.ConnectionProvider
	}
	return ""
}

func (x *AuthLogRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuthLogRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuthLogRequest) GetConnectionDetails() []*ConnectionDetails {
	if x != nil {
		return x.ConnectionDetails
	}
	return nil
}

func (x *AuthLogRequest) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *AuthLogRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuthLogRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *AuthLogRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type ConnectionDetails struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId       string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	OrganizationId     string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ConnectionType     string                 `protobuf:"bytes,3,opt,name=connection_type,json=connectionType,proto3" json:"connection_type,omitempty"`
	ConnectionProvider string                 `protobuf:"bytes,4,opt,name=connection_provider,json=connectionProvider,proto3" json:"connection_provider,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConnectionDetails) Reset() {
	*x = ConnectionDetails{}
	mi := &file_scalekit_v1_auditlogs_auditlogs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionDetails) ProtoMessage() {}

func (x *ConnectionDetails) ProtoReflect() protoreflect.Message {
	mi := &file_scalekit_v1_auditlogs_auditlogs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionDetails.ProtoReflect.Descriptor instead.
func (*ConnectionDetails) Descriptor() ([]byte, []int) {
	return file_scalekit_v1_auditlogs_auditlogs_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionDetails) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ConnectionDetails) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ConnectionDetails) GetConnectionType() string {
	if x != nil {
		return x.ConnectionType
	}
	return ""
}

func (x *ConnectionDetails) GetConnectionProvider() string {
	if x != nil {
		return x.ConnectionProvider
	}
	return ""
}

var File_scalekit_v1_auditlogs_auditlogs_proto protoreflect.FileDescriptor

const file_scalekit_v1_auditlogs_auditlogs_proto_rawDesc = "" +
	"\n" +
	"%scalekit/v1/auditlogs/auditlogs.proto\x12\x15scalekit.v1.auditlogs\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!scalekit/v1/options/options.proto\"\x91\x02\n" +
	"\x12ListAuthLogRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\rR\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x04 \x03(\tR\x06status\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vresource_id\x18\a \x01(\tR\n" +
	"resourceId\"\xcf\x01\n" +
	"\x13ListAuthLogResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12&\n" +
	"\x0fprev_page_token\x18\x02 \x01(\tR\rprevPageToken\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\rR\ttotalSize\x12I\n" +
	"\fauthRequests\x18\x04 \x03(\v2%.scalekit.v1.auditlogs.AuthLogRequestR\fauthRequests\"\xcf\x04\n" +
	"\x0eAuthLogRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12%\n" +
	"\x0eenvironment_id\x18\x02 \x01(\tR\renvironmentId\x12#\n" +
	"\rconnection_id\x18\x03 \x01(\tR\fconnectionId\x12&\n" +
	"\x0fauth_request_id\x18\x04 \x01(\tR\rauthRequestId\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12'\n" +
	"\x0fconnection_type\x18\x06 \x01(\tR\x0econnectionType\x12/\n" +
	"\x13connection_provider\x18\a \x01(\tR\x12connectionProvider\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12W\n" +
	"\x12connection_details\x18\n" +
	" \x03(\v2(.scalekit.v1.auditlogs.ConnectionDetailsR\x11connectionDetails\x12\x1a\n" +
	"\bworkflow\x18\v \x01(\tR\bworkflow\x12\x1f\n" +
	"\vresource_id\x18\f \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_name\x18\r \x01(\tR\fresourceName\x12#\n" +
	"\rresource_type\x18\x0e \x01(\tR\fresourceType\"\xbb\x01\n" +
	"\x11ConnectionDetails\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12'\n" +
	"\x0fconnection_type\x18\x03 \x01(\tR\x0econnectionType\x12/\n" +
	"\x13connection_provider\x18\x04 \x01(\tR\x12connectionProvider2\xb2\x01\n" +
	"\x10AuditLogsService\x12\x9d\x01\n" +
	"\x10ListAuthRequests\x12).scalekit.v1.auditlogs.ListAuthLogRequest\x1a*.scalekit.v1.auditlogs.ListAuthLogResponse\"2\x82\xb5\x18\x02\x18T\x82\xd3\xe4\x93\x02&\x12$/api/v1/logs/authentication/requestsB\xec\x01\n" +
	"\x19com.scalekit.v1.auditlogsB\x0eAuditlogsProtoP\x01ZIgithub.com/scalekit-inc/scalekit-sdk-go/v2/pkg/grpc/scalekit/v1/auditlogs\xa2\x02\x03SVA\xaa\x02\x15Scalekit.V1.Auditlogs\xca\x02\x15Scalekit\\V1\\Auditlogs\xe2\x02!Scalekit\\V1\\Auditlogs\\GPBMetadata\xea\x02\x17Scalekit::V1::Auditlogsb\x06proto3"

var (
	file_scalekit_v1_auditlogs_auditlogs_proto_rawDescOnce sync.Once
	file_scalekit_v1_auditlogs_auditlogs_proto_rawDescData []byte
)

func file_scalekit_v1_auditlogs_auditlogs_proto_rawDescGZIP() []byte {
	file_scalekit_v1_auditlogs_auditlogs_proto_rawDescOnce.Do(func() {
		file_scalekit_v1_auditlogs_auditlogs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scalekit_v1_auditlogs_auditlogs_proto_rawDesc), len(file_scalekit_v1_auditlogs_auditlogs_proto_rawDesc)))
	})
	return file_scalekit_v1_auditlogs_auditlogs_proto_rawDescData
}

var file_scalekit_v1_auditlogs_auditlogs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_scalekit_v1_auditlogs_auditlogs_proto_goTypes = []any{
	(*ListAuthLogRequest)(nil),    // 0: scalekit.v1.auditlogs.ListAuthLogRequest
	(*ListAuthLogResponse)(nil),   // 1: scalekit.v1.auditlogs.ListAuthLogResponse
	(*AuthLogRequest)(nil),        // 2: scalekit.v1.auditlogs.AuthLogRequest
	(*ConnectionDetails)(nil),     // 3: scalekit.v1.auditlogs.ConnectionDetails
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_scalekit_v1_auditlogs_auditlogs_proto_depIdxs = []int32{
	4, // 0: scalekit.v1.auditlogs.ListAuthLogRequest.start_time:type_name -> google.protobuf.Timestamp
	4, // 1: scalekit.v1.auditlogs.ListAuthLogRequest.end_time:type_name -> google.protobuf.Timestamp
	2, // 2: scalekit.v1.auditlogs.ListAuthLogResponse.authRequests:type_name -> scalekit.v1.auditlogs.AuthLogRequest
	4, // 3: scalekit.v1.auditlogs.AuthLogRequest.timestamp:type_name -> google.protobuf.Timestamp
	3, // 4: scalekit.v1.auditlogs.AuthLogRequest.connection_details:type_name -> scalekit.v1.auditlogs.ConnectionDetails
	0, // 5: scalekit.v1.auditlogs.AuditLogsService.ListAuthRequests:input_type -> scalekit.v1.auditlogs.ListAuthLogRequest
	1, // 6: scalekit.v1.auditlogs.AuditLogsService.ListAuthRequests:output_type -> scalekit.v1.auditlogs.ListAuthLogResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_scalekit_v1_auditlogs_auditlogs_proto_init() }
func file_scalekit_v1_auditlogs_auditlogs_proto_init() {
	if File_scalekit_v1_auditlogs_auditlogs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scalekit_v1_auditlogs_auditlogs_proto_rawDesc), len(file_scalekit_v1_auditlogs_auditlogs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scalekit_v1_auditlogs_auditlogs_proto_goTypes,
		DependencyIndexes: file_scalekit_v1_auditlogs_auditlogs_proto_depIdxs,
		MessageInfos:      file_scalekit_v1_auditlogs_auditlogs_proto_msgTypes,
	}.Build()
	File_scalekit_v1_auditlogs_auditlogs_proto = out.File
	file_scalekit_v1_auditlogs_auditlogs_proto_goTypes = nil
	file_scalekit_v1_auditlogs_auditlogs_proto_depIdxs = nil
}
