// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a placeholder file. Regenerate using buf generate.

package tokens

import (
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type CreateTokenRequest struct {
	Token *CreateToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CreateTokenRequest) GetToken() *CreateToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type CreateToken struct {
	OrganizationId string            `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         string            `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CustomClaims   map[string]string `protobuf:"bytes,3,rep,name=custom_claims,json=customClaims,proto3" json:"custom_claims,omitempty"`
	Expiry         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Description    string            `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateToken) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateToken) GetCustomClaims() map[string]string {
	if x != nil {
		return x.CustomClaims
	}
	return nil
}

func (x *CreateToken) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *CreateToken) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateTokenResponse struct {
	Token     string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenId   string `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	TokenInfo *Token `protobuf:"bytes,3,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
}

func (x *CreateTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateTokenResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *CreateTokenResponse) GetTokenInfo() *Token {
	if x != nil {
		return x.TokenInfo
	}
	return nil
}

type ValidateTokenRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	TokenInfo *Token `protobuf:"bytes,1,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
}

func (x *ValidateTokenResponse) GetTokenInfo() *Token {
	if x != nil {
		return x.TokenInfo
	}
	return nil
}

type InvalidateTokenRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *InvalidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ListTokensRequest struct {
	OrganizationId string `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	PageSize       int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
}

func (x *ListTokensRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListTokensRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListTokensRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTokensRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTokensResponse struct {
	Tokens        []*Token `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	TotalCount    int32    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	NextPageToken string   `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	PrevPageToken string   `protobuf:"bytes,4,opt,name=prev_page_token,json=prevPageToken,proto3" json:"prev_page_token,omitempty"`
}

func (x *ListTokensResponse) GetTokens() []*Token {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ListTokensResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListTokensResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListTokensResponse) GetPrevPageToken() string {
	if x != nil {
		return x.PrevPageToken
	}
	return ""
}

type Token struct {
	TokenId                string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	OrganizationId         string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationExternalId string                 `protobuf:"bytes,3,opt,name=organization_external_id,json=organizationExternalId,proto3" json:"organization_external_id,omitempty"`
	UserId                 *string                `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	UserExternalId         *string                `protobuf:"bytes,5,opt,name=user_external_id,json=userExternalId,proto3,oneof" json:"user_external_id,omitempty"`
	CustomClaims           map[string]string      `protobuf:"bytes,6,rep,name=custom_claims,json=customClaims,proto3" json:"custom_claims,omitempty"`
	Expiry                 *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expiry,proto3,oneof" json:"expiry,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Description            *string                `protobuf:"bytes,9,opt,name=description,proto3,oneof" json:"description,omitempty"`
	TokenSuffix            string                 `protobuf:"bytes,10,opt,name=token_suffix,json=tokenSuffix,proto3" json:"token_suffix,omitempty"`
	Email                  *string                `protobuf:"bytes,11,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Roles                  []string               `protobuf:"bytes,12,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *Token) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *Token) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Token) GetOrganizationExternalId() string {
	if x != nil {
		return x.OrganizationExternalId
	}
	return ""
}

func (x *Token) GetUserId() *string {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *Token) GetUserExternalId() *string {
	if x != nil {
		return x.UserExternalId
	}
	return nil
}

func (x *Token) GetCustomClaims() map[string]string {
	if x != nil {
		return x.CustomClaims
	}
	return nil
}

func (x *Token) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *Token) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Token) GetDescription() *string {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Token) GetTokenSuffix() string {
	if x != nil {
		return x.TokenSuffix
	}
	return ""
}

func (x *Token) GetEmail() *string {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *Token) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}
