// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: scalekit/v1/events/events.proto

package eventsconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	events "github.com/scalekit-inc/scalekit-sdk-go/v2/pkg/grpc/scalekit/v1/events"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EventsServiceName is the fully-qualified name of the EventsService service.
	EventsServiceName = "scalekit.v1.events.EventsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EventsServiceListEventsProcedure is the fully-qualified name of the EventsService's ListEvents
	// RPC.
	EventsServiceListEventsProcedure = "/scalekit.v1.events.EventsService/ListEvents"
	// EventsServiceListEventsPaginatedProcedure is the fully-qualified name of the EventsService's
	// ListEventsPaginated RPC.
	EventsServiceListEventsPaginatedProcedure = "/scalekit.v1.events.EventsService/ListEventsPaginated"
	// EventsServiceSendCustomEventProcedure is the fully-qualified name of the EventsService's
	// SendCustomEvent RPC.
	EventsServiceSendCustomEventProcedure = "/scalekit.v1.events.EventsService/SendCustomEvent"
)

// EventsServiceClient is a client for the scalekit.v1.events.EventsService service.
type EventsServiceClient interface {
	ListEvents(context.Context, *connect.Request[events.ListEventsRequest]) (*connect.Response[events.ListEventsResponse], error)
	ListEventsPaginated(context.Context, *connect.Request[events.ListEventsPaginatedRequest]) (*connect.Response[events.ListEventsPaginatedResponse], error)
	SendCustomEvent(context.Context, *connect.Request[events.SendCustomEventRequest]) (*connect.Response[events.SendCustomEventResponse], error)
}

// NewEventsServiceClient constructs a client for the scalekit.v1.events.EventsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventsServiceMethods := events.File_scalekit_v1_events_events_proto.Services().ByName("EventsService").Methods()
	return &eventsServiceClient{
		listEvents: connect.NewClient[events.ListEventsRequest, events.ListEventsResponse](
			httpClient,
			baseURL+EventsServiceListEventsProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		listEventsPaginated: connect.NewClient[events.ListEventsPaginatedRequest, events.ListEventsPaginatedResponse](
			httpClient,
			baseURL+EventsServiceListEventsPaginatedProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("ListEventsPaginated")),
			connect.WithClientOptions(opts...),
		),
		sendCustomEvent: connect.NewClient[events.SendCustomEventRequest, events.SendCustomEventResponse](
			httpClient,
			baseURL+EventsServiceSendCustomEventProcedure,
			connect.WithSchema(eventsServiceMethods.ByName("SendCustomEvent")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventsServiceClient implements EventsServiceClient.
type eventsServiceClient struct {
	listEvents          *connect.Client[events.ListEventsRequest, events.ListEventsResponse]
	listEventsPaginated *connect.Client[events.ListEventsPaginatedRequest, events.ListEventsPaginatedResponse]
	sendCustomEvent     *connect.Client[events.SendCustomEventRequest, events.SendCustomEventResponse]
}

// ListEvents calls scalekit.v1.events.EventsService.ListEvents.
func (c *eventsServiceClient) ListEvents(ctx context.Context, req *connect.Request[events.ListEventsRequest]) (*connect.Response[events.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// ListEventsPaginated calls scalekit.v1.events.EventsService.ListEventsPaginated.
func (c *eventsServiceClient) ListEventsPaginated(ctx context.Context, req *connect.Request[events.ListEventsPaginatedRequest]) (*connect.Response[events.ListEventsPaginatedResponse], error) {
	return c.listEventsPaginated.CallUnary(ctx, req)
}

// SendCustomEvent calls scalekit.v1.events.EventsService.SendCustomEvent.
func (c *eventsServiceClient) SendCustomEvent(ctx context.Context, req *connect.Request[events.SendCustomEventRequest]) (*connect.Response[events.SendCustomEventResponse], error) {
	return c.sendCustomEvent.CallUnary(ctx, req)
}

// EventsServiceHandler is an implementation of the scalekit.v1.events.EventsService service.
type EventsServiceHandler interface {
	ListEvents(context.Context, *connect.Request[events.ListEventsRequest]) (*connect.Response[events.ListEventsResponse], error)
	ListEventsPaginated(context.Context, *connect.Request[events.ListEventsPaginatedRequest]) (*connect.Response[events.ListEventsPaginatedResponse], error)
	SendCustomEvent(context.Context, *connect.Request[events.SendCustomEventRequest]) (*connect.Response[events.SendCustomEventResponse], error)
}

// NewEventsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventsServiceHandler(svc EventsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventsServiceMethods := events.File_scalekit_v1_events_events_proto.Services().ByName("EventsService").Methods()
	eventsServiceListEventsHandler := connect.NewUnaryHandler(
		EventsServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(eventsServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	eventsServiceListEventsPaginatedHandler := connect.NewUnaryHandler(
		EventsServiceListEventsPaginatedProcedure,
		svc.ListEventsPaginated,
		connect.WithSchema(eventsServiceMethods.ByName("ListEventsPaginated")),
		connect.WithHandlerOptions(opts...),
	)
	eventsServiceSendCustomEventHandler := connect.NewUnaryHandler(
		EventsServiceSendCustomEventProcedure,
		svc.SendCustomEvent,
		connect.WithSchema(eventsServiceMethods.ByName("SendCustomEvent")),
		connect.WithHandlerOptions(opts...),
	)
	return "/scalekit.v1.events.EventsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventsServiceListEventsProcedure:
			eventsServiceListEventsHandler.ServeHTTP(w, r)
		case EventsServiceListEventsPaginatedProcedure:
			eventsServiceListEventsPaginatedHandler.ServeHTTP(w, r)
		case EventsServiceSendCustomEventProcedure:
			eventsServiceSendCustomEventHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventsServiceHandler struct{}

func (UnimplementedEventsServiceHandler) ListEvents(context.Context, *connect.Request[events.ListEventsRequest]) (*connect.Response[events.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.events.EventsService.ListEvents is not implemented"))
}

func (UnimplementedEventsServiceHandler) ListEventsPaginated(context.Context, *connect.Request[events.ListEventsPaginatedRequest]) (*connect.Response[events.ListEventsPaginatedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.events.EventsService.ListEventsPaginated is not implemented"))
}

func (UnimplementedEventsServiceHandler) SendCustomEvent(context.Context, *connect.Request[events.SendCustomEventRequest]) (*connect.Response[events.SendCustomEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("scalekit.v1.events.EventsService.SendCustomEvent is not implemented"))
}
